import { batteryMobilityCapability, BATTERY_TECH_IDS } from '../economy/batteryStorage.js?v=20260920-battery1';
import { TELEPHONE_TECH_ID } from '../economy/localCommunications.js?v=20260918-telephone1';
import { RADAR_TECH_ID } from '../military/aviation.js?v=20260918-aviation1';
import { SPACE_TECH_IDS } from './spaceRace.js?v=20260920-space-race1';
import { nationalSatelliteResilience } from './satelliteResilience.js?v=20260921-resilience1';
import { SATELLITE_NAVIGATION_TECH_IDS } from './satelliteNavigation.js?v=20260921-satnav1';

const DAYS_PER_YEAR=365.2425;
const PHOTOVOLTAIC_GENERATION_TECH_ID='photovoltaic_generation';
const clamp=(v,lo=0,hi=1)=>Math.max(lo,Math.min(hi,Number(v)||0));
const nonNegative=(v)=>Math.max(0,Number(v)||0);
const has=(r,id)=>Boolean(r?.unlockedTechIds?.has?.(id));
const polityId=(r)=>r?.governance?.sovereignPolityId||r?.polityId||r?.id;
let nextSatelliteId=1;

export const SATELLITE_ROLES=Object.freeze({SCIENTIFIC:'scientific',WEATHER:'weather',COMMUNICATIONS:'communications',RECONNAISSANCE:'reconnaissance',NAVIGATION:'navigation'});
export const SATELLITE_USE=Object.freeze({CIVILIAN:'civilian',MILITARY:'military',DUAL_USE:'dual_use'});
export const SATELLITE_TYPES=Object.freeze({
  scientific:{use:SATELLITE_USE.CIVILIAN,cash:95,steel:4,fuel:5,requires:[SPACE_TECH_IDS.ORBITAL_SYSTEMS],weights:{scienceObservation:1}},
  weather:{use:SATELLITE_USE.CIVILIAN,cash:130,steel:5,fuel:6,requires:[SPACE_TECH_IDS.ORBITAL_SYSTEMS,RADAR_TECH_ID],weights:{weatherObservation:1,scienceObservation:.25}},
  communications:{use:SATELLITE_USE.DUAL_USE,cash:160,steel:6,fuel:7,requires:[SPACE_TECH_IDS.ORBITAL_SYSTEMS,TELEPHONE_TECH_ID],weights:{civilianCommunications:.9,militaryCommand:.45,remoteControl:.75}},
  reconnaissance:{use:SATELLITE_USE.MILITARY,cash:185,steel:7,fuel:8,requires:[SPACE_TECH_IDS.ORBITAL_SYSTEMS,RADAR_TECH_ID],weights:{militaryReconnaissance:1,militaryCommand:.15}},
  navigation:{use:SATELLITE_USE.DUAL_USE,cash:220,steel:8,fuel:9,requires:[SPACE_TECH_IDS.ORBITAL_SYSTEMS,SATELLITE_NAVIGATION_TECH_IDS.SYSTEM],weights:{navigation:1,civilianCommunications:.15,militaryCommand:.2,remoteControl:.35}},
});

function groupedPolities(regions){const groups=new Map();for(const r of regions||[]){const id=polityId(r);if(!groups.has(id))groups.set(id,[]);groups.get(id).push(r);}return groups;}
function carrierRegion(members){const withProgramme=members.filter(r=>r.spaceProgramme).sort((a,b)=>(b.spaceProgramme?.completedMilestones?.length||0)-(a.spaceProgramme?.completedMilestones?.length||0));return withProgramme[0]||[...members].sort((a,b)=>(b.population||0)-(a.population||0))[0]||null;}
function ensureOrbitalState(region){region.orbitalProgramme||={satellites:[],lastLaunchTick:null,totalLaunches:0,totalFailures:0};const s=region.orbitalProgramme;s.satellites||=[];s.groundControlCondition=clamp(s.groundControlCondition??1);s.launchInfrastructureCondition=clamp(s.launchInfrastructureCondition??1);return s;}
export function syncNextSatelliteId(regions=[]){let max=0;for(const r of regions)for(const s of r.orbitalProgramme?.satellites||[])max=Math.max(max,Number(String(s.id||'').replace(/\D/g,''))||0);nextSatelliteId=max+1;}
function nationalResources(members){return{treasury:members.reduce((s,r)=>s+nonNegative(r.treasury),0),steel:members.reduce((s,r)=>s+nonNegative(r.stockpile?.steel),0),fuel:members.reduce((s,r)=>s+nonNegative(r.stockpile?.petrol),0)};}
function consumeAcross(members,key,amount){let remaining=Math.max(0,amount);const available=(r)=>key==='treasury'?nonNegative(r.treasury):nonNegative(r.stockpile?.[key==='fuel'?'petrol':key]);for(const r of [...members].sort((a,b)=>available(b)-available(a))){if(remaining<=1e-9)break;const take=Math.min(available(r),remaining);if(key==='treasury')r.treasury=available(r)-take;else{r.stockpile||={};const k=key==='fuel'?'petrol':key;r.stockpile[k]=available(r)-take;}remaining-=take;}return amount-remaining;}
function technologyAvailable(members,id){return members.some(r=>has(r,id));}
function roleAvailable(members,role){const t=SATELLITE_TYPES[role];return Boolean(t&&(t.requires||[]).every(id=>technologyAvailable(members,id)));}
function batteryCapability(members){let best={available:false,satelliteUtility:0,chemistry:null};for(const r of members){const b=batteryMobilityCapability(r);if((b.satelliteUtility||0)>(best.satelliteUtility||0))best=b;}return best;}
function powerPackage(members){const b=batteryCapability(members),solar=technologyAvailable(members,PHOTOVOLTAIC_GENERATION_TECH_ID),rechargeable=members.some(r=>has(r,BATTERY_TECH_IDS.LEAD_ACID));if(solar&&rechargeable)return{mode:'solar_rechargeable',designLifeDays:DAYS_PER_YEAR*(4.5+(b.satelliteUtility||.15)*5.5),batteryChemistry:b.chemistry||'lead_acid'};return{mode:'battery_only',designLifeDays:55+(b.satelliteUtility||.15)*155,batteryChemistry:b.chemistry||'primary_cells'};}
function satelliteWeight(s,type){return clamp((s.condition??1)*(s.serviceFraction??1))*type;}
function orbitalCapabilityFrom(satellites){const raw={scienceObservation:0,weatherObservation:0,civilianCommunications:0,militaryReconnaissance:0,militaryCommand:0,remoteControl:0,navigation:0};for(const s of satellites){if(!s.operational)continue;const type=SATELLITE_TYPES[s.role];if(!type)continue;for(const [key,w] of Object.entries(type.weights||{}))raw[key]+=satelliteWeight(s,w);}const out={};for(const [key,value] of Object.entries(raw))out[key]=clamp(1-Math.exp(-value*.72));out.droneBeyondLineOfSightControl=out.remoteControl;out.operationalSatellites=satellites.filter(s=>s.operational).length;return out;}
function applyGroundControl(capability,state,resilience){const damaged=clamp(state?.groundControlCondition??1),redundancy=clamp(resilience?.groundControlRedundancy||0),control=clamp(damaged+(1-damaged)*redundancy),observation=.45+.55*control;capability.civilianCommunications*=control;capability.militaryCommand*=control;capability.remoteControl*=control;capability.droneBeyondLineOfSightControl*=control;capability.navigation*=control;capability.militaryReconnaissance*=observation;capability.weatherObservation*=observation;capability.scienceObservation*=observation;capability.groundControlCondition=control;capability.launchInfrastructureCondition=clamp(state?.launchInfrastructureCondition??1);capability.groundControlRedundancy=redundancy;capability.proliferatedLeo=Boolean(resilience?.proliferatedLeo);return capability;}
function syncSupport(members,satellites,state){const resilience=nationalSatelliteResilience(members),cap=applyGroundControl(orbitalCapabilityFrom(satellites),state,resilience);for(const r of members)r.orbitalSupport={...cap};return cap;}
export function orbitalSupport(region){return region?.orbitalSupport||{scienceObservation:0,weatherObservation:0,civilianCommunications:0,militaryReconnaissance:0,militaryCommand:0,remoteControl:0,navigation:0,droneBeyondLineOfSightControl:0,operationalSatellites:0,groundControlCondition:1,launchInfrastructureCondition:1,groundControlRedundancy:0,proliferatedLeo:false};}

function launchProfile(members,type){const resilience=nationalSatelliteResilience(members);if(!resilience.proliferatedLeo)return{cash:type.cash,steel:type.steel,fuel:type.fuel,serviceFraction:1,architecture:'single_satellite'};return{cash:type.cash*.34,steel:type.steel*.34,fuel:type.fuel*.42,serviceFraction:.28,architecture:'proliferated_leo'};}
export function launchSatellite(members,role,currentTick,{free=false}= {}){const carrier=carrierRegion(members);if(!carrier)return{launched:false,reason:'no_space_programme'};if(!roleAvailable(members,role))return{launched:false,reason:'technology_not_ready'};const state=ensureOrbitalState(carrier);if(!free&&state.launchInfrastructureCondition<.18)return{launched:false,reason:'launch_infrastructure_disabled'};const type=SATELLITE_TYPES[role],profile=launchProfile(members,type),resources=nationalResources(members);if(!free&&(resources.treasury<profile.cash||resources.steel<profile.steel||resources.fuel<profile.fuel))return{launched:false,reason:'insufficient_resources'};if(!free){consumeAcross(members,'treasury',profile.cash);consumeAcross(members,'steel',profile.steel);consumeAcross(members,'fuel',profile.fuel);}const power=powerPackage(members),resilience=nationalSatelliteResilience(members);const sat={id:`sat_${nextSatelliteId++}`,role,use:type.use,ownerPolityId:polityId(carrier),launchRegionId:carrier.id,launchedTick:currentTick,powerMode:power.mode,batteryChemistry:power.batteryChemistry,designLifeDays:power.designLifeDays,remainingLifeDays:power.designLifeDays,condition:1,operational:true,architecture:profile.architecture,serviceFraction:profile.serviceFraction,frequencyAgility:resilience.frequencyAgility,manoeuvreReserve:resilience.manoeuvreEvasion};state.satellites.push(sat);state.lastLaunchTick=currentTick;state.totalLaunches++;syncSupport(members,state.satellites,state);return{launched:true,satellite:sat,cost:free?{cash:0,steel:0,fuel:0}:{cash:profile.cash,steel:profile.steel,fuel:profile.fuel}};}

function chooseNextRole(members,satellites){const support=orbitalCapabilityFrom(satellites),c=[];if(roleAvailable(members,'scientific'))c.push(['scientific',support.scienceObservation]);if(roleAvailable(members,'weather'))c.push(['weather',support.weatherObservation]);if(roleAvailable(members,'communications'))c.push(['communications',Math.max(support.civilianCommunications,support.remoteControl)]);if(roleAvailable(members,'reconnaissance'))c.push(['reconnaissance',support.militaryReconnaissance]);if(roleAvailable(members,'navigation'))c.push(['navigation',support.navigation]);c.sort((a,b)=>a[1]-b[1]);return c[0]?.[0]||null;}
function programmeReady(members){return members.some(r=>r.spaceProgramme?.completedMilestones?.includes?.('first_satellite'))&&technologyAvailable(members,SPACE_TECH_IDS.ORBITAL_SYSTEMS);}
function repairGroundInfrastructure(carrier,state,days){if(state.groundControlCondition>=.999&&state.launchInfrastructureCondition>=.999)return;const pace=Math.max(.1,days/7),cash=Math.min(nonNegative(carrier.treasury),1.4*pace),steel=Math.min(nonNegative(carrier.stockpile?.steel),.12*pace);if(cash<=0||steel<=0)return;carrier.treasury-=cash;carrier.stockpile.steel-=steel;const repair=.012*pace*Math.min(1,cash/(1.4*pace),steel/(.12*pace));state.groundControlCondition=clamp(state.groundControlCondition+repair);state.launchInfrastructureCondition=clamp(state.launchInfrastructureCondition+repair*.82);}

export function tickOrbitalSatellites(regions,currentTick,rng=Math.random,elapsedDays=7){const events=[],groups=groupedPolities(regions);syncNextSatelliteId(regions);for(const members of groups.values()){const carrier=carrierRegion(members);if(!carrier||!programmeReady(members))continue;const state=ensureOrbitalState(carrier),days=Math.max(0,Number(elapsedDays)||0),resilience=nationalSatelliteResilience(members);repairGroundInfrastructure(carrier,state,days);if(!state.satellites.length){const first=launchSatellite(members,'scientific',currentTick,{free:true});if(first.launched)events.push({type:'satellite_launched',regionId:carrier.id,tick:currentTick,title:'First orbital satellite enters service',satelliteId:first.satellite.id,role:first.satellite.role,use:first.satellite.use});}for(const sat of state.satellites){if(!sat.operational)continue;sat.frequencyAgility=Math.max(sat.frequencyAgility||0,resilience.frequencyAgility);sat.manoeuvreReserve=Math.max(sat.manoeuvreReserve||0,resilience.manoeuvreEvasion);sat.remainingLifeDays=Math.max(0,nonNegative(sat.remainingLifeDays)-days);const lifeFraction=sat.designLifeDays>0?sat.remainingLifeDays/sat.designLifeDays:0;sat.condition=clamp(Math.min(sat.condition??1,.45+lifeFraction*.55));if(sat.remainingLifeDays<=0){sat.operational=false;sat.condition=0;events.push({type:'satellite_end_of_life',regionId:carrier.id,tick:currentTick,satelliteId:sat.id,role:sat.role});}}syncSupport(members,state.satellites,state);const since=state.lastLaunchTick===null?99999:Math.max(0,currentTick-state.lastLaunchTick),role=chooseNextRole(members,state.satellites);if(!role)continue;const minInterval=resilience.rapidReplacement?Math.max(4,Math.round(26*(1-resilience.rapidReplacement))):26;if(since<minInterval)continue;const type=SATELLITE_TYPES[role],profile=launchProfile(members,type),resources=nationalResources(members),affordability=Math.min(resources.treasury/Math.max(1,profile.cash),resources.steel/Math.max(.1,profile.steel),resources.fuel/Math.max(.1,profile.fuel)),operational=state.satellites.filter(s=>s.operational).length;const annualChance=clamp((.10+Math.min(.22,operational*.02)+(affordability>=2?.12:0)+(resilience.rapidReplacement?.12:0)+(resilience.proliferatedLeo?.18:0))*state.launchInfrastructureCondition);if(affordability<1||rng()>=1-Math.pow(1-annualChance,days/DAYS_PER_YEAR))continue;const launched=launchSatellite(members,role,currentTick);if(launched.launched)events.push({type:'satellite_launched',regionId:carrier.id,tick:currentTick,title:`${role} satellite launched`,satelliteId:launched.satellite.id,role,use:launched.satellite.use,cost:launched.cost,architecture:launched.satellite.architecture});}return events;}
