import { SPACE_TECH_IDS } from './spaceRace.js?v=20260921-satnav1';

const DAYS_PER_YEAR=365.2425;
const clamp=(v,lo=0,hi=1)=>Math.max(lo,Math.min(hi,Number(v)||0));
const has=(r,id)=>Boolean(r?.unlockedTechIds?.has?.(id));
const polityId=r=>r?.governance?.sovereignPolityId||r?.polityId||r?.id;

export const SATELLITE_NAVIGATION_TECH_IDS=Object.freeze({SYSTEM:'satellite_navigation_systems',CIVIL_RECEIVERS:'civil_satellite_navigation_receivers',PRECISION_GUIDANCE:'satellite_aided_precision_guidance',INTEGRATED_NAVIGATION:'integrated_satellite_inertial_navigation'});

function electronics(region){const c=region?.industrialPlants?.componentCapability||{};return clamp(Math.max(c.electronics||0,c.radio_navigation||0,c.radar_set||0));}
function precision(region){return clamp(region?.industrialSupply?.capability?.precision_machining||0);}
function manufacture(region){return clamp(region?.structuralTransformation?.capability?.manufacture||0);}
function orbitalExperience(region){return clamp(((region?.spaceProgramme?.completedMilestones?.length||0)*.07)+((region?.orbitalProgramme?.totalLaunches||0)*.035));}
function annual(rate,days){return 1-Math.pow(1-clamp(rate,0,.95),Math.max(0,Number(days)||0)/DAYS_PER_YEAR);}

export function tickSatelliteNavigationBreakthroughs(regions,currentTick,rng=Math.random,elapsedDays=7){const events=[];for(const region of regions||[]){region.unlockedTechIds||=new Set();const e=electronics(region),p=precision(region),m=manufacture(region),xp=orbitalExperience(region);if(!has(region,SATELLITE_NAVIGATION_TECH_IDS.SYSTEM)&&has(region,SPACE_TECH_IDS.ORBITAL_SYSTEMS)&&has(region,'radar')&&e>.58&&p>.50&&xp>.16){if(rng()<annual(.00065+e*.0045+p*.0035+xp*.006,elapsedDays)){region.unlockedTechIds.add(SATELLITE_NAVIGATION_TECH_IDS.SYSTEM);events.push({type:'satellite_navigation_breakthrough',techId:SATELLITE_NAVIGATION_TECH_IDS.SYSTEM,regionId:region.id,tick:currentTick,title:'Satellite navigation system'});continue;}}if(!has(region,SATELLITE_NAVIGATION_TECH_IDS.CIVIL_RECEIVERS)&&has(region,SATELLITE_NAVIGATION_TECH_IDS.SYSTEM)&&e>.66&&m>.56){if(rng()<annual(.0009+e*.005+m*.004,elapsedDays)){region.unlockedTechIds.add(SATELLITE_NAVIGATION_TECH_IDS.CIVIL_RECEIVERS);events.push({type:'satellite_navigation_breakthrough',techId:SATELLITE_NAVIGATION_TECH_IDS.CIVIL_RECEIVERS,regionId:region.id,tick:currentTick,title:'Civil satellite-navigation receivers'});continue;}}if(!has(region,SATELLITE_NAVIGATION_TECH_IDS.PRECISION_GUIDANCE)&&has(region,SATELLITE_NAVIGATION_TECH_IDS.SYSTEM)&&has(region,'guided_missile_guidance')&&e>.70&&p>.65){if(rng()<annual(.00055+e*.004+p*.004+xp*.005,elapsedDays)){region.unlockedTechIds.add(SATELLITE_NAVIGATION_TECH_IDS.PRECISION_GUIDANCE);events.push({type:'satellite_navigation_breakthrough',techId:SATELLITE_NAVIGATION_TECH_IDS.PRECISION_GUIDANCE,regionId:region.id,tick:currentTick,title:'Satellite-aided precision guidance'});continue;}}if(!has(region,SATELLITE_NAVIGATION_TECH_IDS.INTEGRATED_NAVIGATION)&&has(region,SATELLITE_NAVIGATION_TECH_IDS.PRECISION_GUIDANCE)&&e>.78&&p>.72&&m>.68){if(rng()<annual(.00034+e*.0035+p*.003+m*.003,elapsedDays)){region.unlockedTechIds.add(SATELLITE_NAVIGATION_TECH_IDS.INTEGRATED_NAVIGATION);events.push({type:'satellite_navigation_breakthrough',techId:SATELLITE_NAVIGATION_TECH_IDS.INTEGRATED_NAVIGATION,regionId:region.id,tick:currentTick,title:'Integrated satellite and inertial navigation'});}}}return events;}

function navigationSatellites(region){return (region?.orbitalProgramme?.satellites||[]).filter(s=>s.operational&&s.role==='navigation');}
function constellationCoverage(count){if(count<=0)return 0;if(count<4)return .10+count*.07;if(count<12)return .32+(count-4)*.045;if(count<24)return .68+(count-12)*.022;return clamp(.94+(count-24)*.004,0,1);}

export function satelliteNavigationCapability(region){const sats=navigationSatellites(region),count=sats.length,coverage=constellationCoverage(count),liveSignal=clamp(region?.orbitalSupport?.navigation||0),control=clamp(region?.orbitalSupport?.groundControlCondition??1),resilient=clamp(region?.satelliteResilience?.lessons||0);const signalQuality=count>0?clamp(Math.min(coverage,liveSignal*1.5)*(.72+.28*control)):0;const civilianReceivers=has(region,SATELLITE_NAVIGATION_TECH_IDS.CIVIL_RECEIVERS),precisionGuidance=has(region,SATELLITE_NAVIGATION_TECH_IDS.PRECISION_GUIDANCE),integrated=has(region,SATELLITE_NAVIGATION_TECH_IDS.INTEGRATED_NAVIGATION);const civilianNavigation=civilianReceivers?clamp(signalQuality*(.72+.18*electronics(region))):0;const militaryNavigation=has(region,SATELLITE_NAVIGATION_TECH_IDS.SYSTEM)?clamp(signalQuality*(.76+(integrated?.14:.04))):0;const precisionStrike=precisionGuidance?clamp(militaryNavigation*(.55+.25*precision(region)+(integrated?.16:0))):0;const contestedRetention=integrated?clamp(.32+resilient*.26+electronics(region)*.18):clamp(.08+resilient*.12);return{available:count>0&&has(region,SATELLITE_NAVIGATION_TECH_IDS.SYSTEM),satellites:count,coverage,liveSignal,signalQuality,civilianNavigation,militaryNavigation,precisionStrike,contestedRetention,civilianTransportEfficiency:civilianReceivers?clamp(.03+civilianNavigation*.14):0,routePlanning:civilianReceivers?clamp(.05+civilianNavigation*.22):0,airNavigation:clamp(militaryNavigation*(precisionGuidance?.92:.58)),navalNavigation:clamp(militaryNavigation*(civilianReceivers?.78:.56)),droneNavigation:clamp(militaryNavigation*(precisionGuidance?.96:.62))};}

function civilianTransportState(capability){const nav=capability.civilianNavigation;return{enabled:nav>.02,routePlanning:capability.routePlanning,roadDispatchEfficiency:clamp(1+capability.civilianTransportEfficiency*.45,1,1.08),freightRoutingEfficiency:clamp(1+capability.civilianTransportEfficiency*.60,1,1.10),maritimeRoutingEfficiency:clamp(1+nav*.055,1,1.055),civilAviationRoutingEfficiency:clamp(1+nav*.075,1,1.075),emergencyDispatchEfficiency:clamp(1+nav*.06,1,1.06)};}

export function syncSatelliteNavigationServices(regions=[]){const groups=new Map();for(const r of regions){const id=polityId(r);if(!groups.has(id))groups.set(id,[]);groups.get(id).push(r);}for(const members of groups.values()){const carrier=[...members].sort((a,b)=>(b.orbitalProgramme?.satellites?.length||0)-(a.orbitalProgramme?.satellites?.length||0))[0];if(!carrier)continue;const capability=satelliteNavigationCapability(carrier),transport=civilianTransportState(capability);for(const r of members){r.satelliteNavigation={...capability};r.civilianNavigationTransport={...transport};}}}

export function navigationService(region){return region?.satelliteNavigation||satelliteNavigationCapability(region);}
export function civilianNavigationTransport(region){return region?.civilianNavigationTransport||civilianTransportState(navigationService(region));}
