import { PETROLEUM_CRACKING_TECH_ID } from '../technology/petroleum.js?v=20260921-synth-pesticides1';
import { precisionPesticideDemandMultiplier, precisionResidueMultiplier } from './precisionAgriculture.js?v=20260921-precision-ag1';

const DAYS_PER_YEAR=365.2425;
const clamp=(v,lo=0,hi=1)=>Math.max(lo,Math.min(hi,Number(v)||0));
const nonNegative=v=>Math.max(0,Number(v)||0);
const PLANT_FOODS=Object.freeze(['staple_grains','pulses','fruit_vegetables']);

export const CHEMICAL_PEST_CONTROL_TECH_ID='chemical_pest_control';
export const SYNTHETIC_PESTICIDES_TECH_ID='synthetic_pesticides';
export const INTEGRATED_PEST_MANAGEMENT_TECH_ID='integrated_pest_management';
export const SELECTIVE_PESTICIDES_TECH_ID='selective_pesticides';

const HECTARES_PER_TREATMENT_UNIT=150;
const SULFUR_PER_UNIT=.65;
const COPPER_PER_UNIT=.24;
const RESERVE_YEARS=.25;
const MAX_FIRST_GEN_CONTROL=.62;
const MAX_SYNTHETIC_CONTROL=.88;
const MAX_SELECTIVE_CONTROL=.84;
const MAX_IPM_CONTROL=.34;
const MAX_TOTAL_CONTROL=.93;
const PETROL_FEEDSTOCK_PER_UNIT=.72;
const SULFUR_SYNTHETIC_PER_UNIT=.18;
const PETROL_SELECTIVE_PER_UNIT=.58;
const SULFUR_SELECTIVE_PER_UNIT=.07;

export function ensureAgriculturalPesticides(region){
  region.agriculturalPesticides||={};
  const s=region.agriculturalPesticides;
  for(const [k,v] of Object.entries({productionExperience:0,syntheticProductionExperience:0,selectiveProductionExperience:0,applicationExperience:0,ipmExperience:0,lastProduced:0,lastSyntheticProduced:0,lastSelectiveProduced:0,lastApplied:0,lastSyntheticApplied:0,lastSelectiveApplied:0,applicationCoverage:0,syntheticCoverage:0,selectiveCoverage:0,ipmEffectiveness:0,chemicalDemandReduction:0,resistance:0,syntheticResistance:0,selectiveResistance:0,residueLoad:0,ecologicalPressure:0,toxicityPressure:0,productionCapability:0,sulfurUsed:0,copperUsed:0,petroleumFeedstockUsed:0}))if(!Number.isFinite(s[k]))s[k]=v;
  s.controlByCategory||={};s.ipmControlByCategory||={};
  for(const id of PLANT_FOODS){if(!Number.isFinite(s.controlByCategory[id]))s.controlByCategory[id]=0;if(!Number.isFinite(s.ipmControlByCategory[id]))s.ipmControlByCategory[id]=0;}
  return s;
}

function cultivatedHa(region){const cultivated=nonNegative(region.agriculturalLand?.cultivatedHa);if(cultivated>0)return cultivated;return nonNegative(region.agriculturalLand?.availableArableHa)*clamp(region.agriculturalLand?.cultivationShare||0);}
function outbreakSignal(region){const pests=region.agriculturalPests||{};let weighted=0,total=0;const mix=region.foodDiversity?.productionMix||{};for(const id of PLANT_FOODS){const w=Math.max(.05,nonNegative(mix[id]));const severity=clamp(pests.outbreakSeverity?.[id]||0);weighted+=severity*w;total+=w;}return total>0?clamp(weighted/total):0;}
function cropDiversity(region){const mix=region.foodDiversity?.productionMix||{};const values=PLANT_FOODS.map(id=>nonNegative(mix[id]));const total=values.reduce((a,b)=>a+b,0)||1;const hhi=values.reduce((sum,v)=>{const p=v/total;return sum+p*p;},0);return clamp((1-hhi)/(1-1/3));}
function industrialReadiness(region){const manufacture=clamp(region.structuralTransformation?.capability?.manufacture||0),machining=clamp(region.industrialSupply?.capability?.precision_machining||0),factory=clamp(nonNegative(region.industrialPlants?.factoryCapacity)/35);return clamp(manufacture*.46+machining*.22+factory*.32);}
function managementReadiness(region){const admin=clamp(region.governance?.administrativeControl||region.governance?.administration?.recordKeeping||0),literacy=clamp(region.education?.literacyRate||region.massEducation?.literacyRate||0),diversity=cropDiversity(region),experience=clamp(ensureAgriculturalPesticides(region).applicationExperience);return clamp(diversity*.34+admin*.24+literacy*.18+experience*.24);}

export function pesticideProductionCapability(region){if(!region.unlockedTechIds?.has?.(CHEMICAL_PEST_CONTROL_TECH_ID))return 0;const s=ensureAgriculturalPesticides(region);return clamp(industrialReadiness(region)*.82+s.productionExperience*.18);}
function syntheticProductionCapability(region){if(!region.unlockedTechIds?.has?.(SYNTHETIC_PESTICIDES_TECH_ID))return 0;const s=ensureAgriculturalPesticides(region);return clamp(industrialReadiness(region)*.70+s.productionExperience*.10+s.syntheticProductionExperience*.20);}
function selectiveProductionCapability(region){if(!region.unlockedTechIds?.has?.(SELECTIVE_PESTICIDES_TECH_ID))return 0;const s=ensureAgriculturalPesticides(region);return clamp(industrialReadiness(region)*.58+s.syntheticProductionExperience*.18+s.selectiveProductionExperience*.24);}
function annualFullTreatmentDemand(region){if(!region.unlockedTechIds?.has?.(CHEMICAL_PEST_CONTROL_TECH_ID))return 0;return cultivatedHa(region)/HECTARES_PER_TREATMENT_UNIT*precisionPesticideDemandMultiplier(region);}

function producePesticide(region,wanted,elapsedDays){const s=ensureAgriculturalPesticides(region);if(!region.unlockedTechIds?.has?.(CHEMICAL_PEST_CONTROL_TECH_ID)||wanted<=0)return 0;region.stockpile||={};const years=Math.max(0,Number(elapsedDays)||0)/DAYS_PER_YEAR,capability=pesticideProductionCapability(region),factory=nonNegative(region.industrialPlants?.factoryCapacity),capacity=factory*Math.max(.05,.12+.30*capability)*years,sulfur=nonNegative(region.stockpile.sulfur),copper=nonNegative(region.stockpile.copper),output=Math.min(wanted,capacity,sulfur/SULFUR_PER_UNIT,copper/COPPER_PER_UNIT);if(output<=0)return 0;s.sulfurUsed+=output*SULFUR_PER_UNIT;s.copperUsed+=output*COPPER_PER_UNIT;region.stockpile.sulfur=Math.max(0,sulfur-output*SULFUR_PER_UNIT);region.stockpile.copper=Math.max(0,copper-output*COPPER_PER_UNIT);region.stockpile.pesticide=nonNegative(region.stockpile.pesticide)+output;s.lastProduced=output;s.productionExperience=clamp(s.productionExperience+.006*clamp(output/Math.max(.001,capacity))*(1-s.productionExperience));return output;}
function produceSyntheticPesticide(region,wanted,elapsedDays){const s=ensureAgriculturalPesticides(region),tech=region.unlockedTechIds||new Set();if(!tech.has(SYNTHETIC_PESTICIDES_TECH_ID)||!tech.has(PETROLEUM_CRACKING_TECH_ID)||wanted<=0)return 0;region.stockpile||={};const years=Math.max(0,Number(elapsedDays)||0)/DAYS_PER_YEAR,capability=syntheticProductionCapability(region),factory=nonNegative(region.industrialPlants?.factoryCapacity),capacity=factory*Math.max(.04,.10+.34*capability)*years,petrol=nonNegative(region.stockpile.petrol),sulfur=nonNegative(region.stockpile.sulfur),output=Math.min(wanted,capacity,petrol/PETROL_FEEDSTOCK_PER_UNIT,sulfur/SULFUR_SYNTHETIC_PER_UNIT);if(output<=0)return 0;const petrolUsed=output*PETROL_FEEDSTOCK_PER_UNIT;s.petroleumFeedstockUsed+=petrolUsed;s.sulfurUsed+=output*SULFUR_SYNTHETIC_PER_UNIT;region.stockpile.petrol=Math.max(0,petrol-petrolUsed);region.stockpile.sulfur=Math.max(0,sulfur-output*SULFUR_SYNTHETIC_PER_UNIT);region.stockpile.synthetic_pesticide=nonNegative(region.stockpile.synthetic_pesticide)+output;s.lastSyntheticProduced=output;s.syntheticProductionExperience=clamp(s.syntheticProductionExperience+.007*clamp(output/Math.max(.001,capacity))*(1-s.syntheticProductionExperience));return output;}
function produceSelectivePesticide(region,wanted,elapsedDays){const s=ensureAgriculturalPesticides(region),tech=region.unlockedTechIds||new Set();if(!tech.has(SELECTIVE_PESTICIDES_TECH_ID)||!tech.has(PETROLEUM_CRACKING_TECH_ID)||wanted<=0)return 0;region.stockpile||={};const years=Math.max(0,Number(elapsedDays)||0)/DAYS_PER_YEAR,capability=selectiveProductionCapability(region),factory=nonNegative(region.industrialPlants?.factoryCapacity),capacity=factory*Math.max(.035,.08+.28*capability)*years,petrol=nonNegative(region.stockpile.petrol),sulfur=nonNegative(region.stockpile.sulfur),output=Math.min(wanted,capacity,petrol/PETROL_SELECTIVE_PER_UNIT,sulfur/SULFUR_SELECTIVE_PER_UNIT);if(output<=0)return 0;const petrolUsed=output*PETROL_SELECTIVE_PER_UNIT;s.petroleumFeedstockUsed+=petrolUsed;s.sulfurUsed+=output*SULFUR_SELECTIVE_PER_UNIT;region.stockpile.petrol=Math.max(0,petrol-petrolUsed);region.stockpile.sulfur=Math.max(0,sulfur-output*SULFUR_SELECTIVE_PER_UNIT);region.stockpile.selective_pesticide=nonNegative(region.stockpile.selective_pesticide)+output;s.lastSelectiveProduced=output;s.selectiveProductionExperience=clamp(s.selectiveProductionExperience+.006*clamp(output/Math.max(.001,capacity))*(1-s.selectiveProductionExperience));return output;}

function ipmControls(region,s,years){for(const id of PLANT_FOODS)s.ipmControlByCategory[id]=0;if(!region.unlockedTechIds?.has?.(INTEGRATED_PEST_MANAGEMENT_TECH_ID)){s.ipmEffectiveness=0;s.chemicalDemandReduction=0;return;}const readiness=managementReadiness(region),learningTarget=clamp(.28+readiness*.72),adjustment=1-Math.exp(-.45*years);s.ipmExperience=clamp(s.ipmExperience+(learningTarget-s.ipmExperience)*adjustment);s.ipmEffectiveness=clamp(readiness*.55+s.ipmExperience*.45);s.chemicalDemandReduction=clamp(.12+s.ipmEffectiveness*.42,0,.52);const pests=region.agriculturalPests||{},diversity=cropDiversity(region);for(const id of PLANT_FOODS){const severity=clamp(pests.outbreakSeverity?.[id]||0),thresholdTargeting=clamp(.35+severity*.65);s.ipmControlByCategory[id]=clamp(MAX_IPM_CONTROL*s.ipmEffectiveness*(.62+.38*diversity)*thresholdTargeting,0,MAX_IPM_CONTROL);}}
function combineControl(...parts){return clamp(1-parts.reduce((remaining,p)=>remaining*(1-clamp(p)),1),0,MAX_TOTAL_CONTROL);}

function applyPesticides(region,elapsedDays){
  const s=ensureAgriculturalPesticides(region),years=Math.max(0,Number(elapsedDays)||0)/DAYS_PER_YEAR,tech=region.unlockedTechIds||new Set();for(const id of PLANT_FOODS)s.controlByCategory[id]=0;ipmControls(region,s,years);
  if(!tech.has(CHEMICAL_PEST_CONTROL_TECH_ID)){s.lastApplied=0;s.lastSyntheticApplied=0;s.lastSelectiveApplied=0;s.applicationCoverage=0;s.syntheticCoverage=0;s.selectiveCoverage=0;for(const id of PLANT_FOODS)s.controlByCategory[id]=s.ipmControlByCategory[id];return 0;}
  const signal=outbreakSignal(region),annual=annualFullTreatmentDemand(region),thresholdFloor=tech.has(INTEGRATED_PEST_MANAGEMENT_TECH_ID)?.025:.08,rawIntensity=clamp(thresholdFloor+signal*(1-thresholdFloor),thresholdFloor,1),intensity=clamp(rawIntensity*(1-s.chemicalDemandReduction),.015,1),needed=annual*years*intensity;
  const selectivePreferred=tech.has(SELECTIVE_PESTICIDES_TECH_ID)&&signal>.08,selectiveAvailable=nonNegative(region.stockpile?.selective_pesticide),selectiveApplied=Math.min(selectiveAvailable,selectivePreferred?needed:0);if(region.stockpile)region.stockpile.selective_pesticide=Math.max(0,selectiveAvailable-selectiveApplied);let residualNeed=Math.max(0,needed-selectiveApplied);
  const syntheticPreferred=tech.has(SYNTHETIC_PESTICIDES_TECH_ID)&&signal>.18,syntheticAvailable=nonNegative(region.stockpile?.synthetic_pesticide),syntheticApplied=Math.min(syntheticAvailable,syntheticPreferred?residualNeed:0);if(region.stockpile)region.stockpile.synthetic_pesticide=Math.max(0,syntheticAvailable-syntheticApplied);residualNeed=Math.max(0,residualNeed-syntheticApplied);
  const mineralAvailable=nonNegative(region.stockpile?.pesticide),mineralApplied=Math.min(mineralAvailable,residualNeed);if(region.stockpile)region.stockpile.pesticide=Math.max(0,mineralAvailable-mineralApplied);
  s.lastApplied=mineralApplied;s.lastSyntheticApplied=syntheticApplied;s.lastSelectiveApplied=selectiveApplied;s.selectiveCoverage=needed>0?clamp(selectiveApplied/needed):0;s.syntheticCoverage=needed>0?clamp(syntheticApplied/needed):0;s.applicationCoverage=needed>0?clamp((selectiveApplied+syntheticApplied+mineralApplied)/needed):0;
  const mineralPotency=MAX_FIRST_GEN_CONTROL*(1-s.resistance*.78),syntheticPotency=MAX_SYNTHETIC_CONTROL*(1-s.syntheticResistance*.72),selectivePotency=MAX_SELECTIVE_CONTROL*(1-s.selectiveResistance*.58),pests=region.agriculturalPests||{};
  for(const id of PLANT_FOODS){const categorySeverity=clamp(pests.outbreakSeverity?.[id]||0),targeting=clamp(.35+categorySeverity*.85,.35,1),selectiveTargeting=clamp(.58+categorySeverity*.58,.58,1),mineralCoverage=needed>0?clamp(mineralApplied/needed):0;const chemicalControl=clamp(mineralCoverage*mineralPotency*targeting+s.syntheticCoverage*syntheticPotency*targeting+s.selectiveCoverage*selectivePotency*selectiveTargeting,0,MAX_SYNTHETIC_CONTROL);s.controlByCategory[id]=combineControl(s.ipmControlByCategory[id],chemicalControl);}
  if(mineralApplied>0)s.resistance=clamp(s.resistance+years*(.035+.16*clamp(mineralApplied/Math.max(.001,needed)))*(1-s.resistance));else s.resistance=clamp(s.resistance*Math.exp(-.045*years));
  if(syntheticApplied>0)s.syntheticResistance=clamp(s.syntheticResistance+years*(.08+.30*s.syntheticCoverage)*(1-s.syntheticResistance));else s.syntheticResistance=clamp(s.syntheticResistance*Math.exp(-.025*years));
  if(selectiveApplied>0)s.selectiveResistance=clamp(s.selectiveResistance+years*(.035+.14*s.selectiveCoverage)*(1-s.selectiveResistance));else s.selectiveResistance=clamp(s.selectiveResistance*Math.exp(-.032*years));
  if(mineralApplied+syntheticApplied+selectiveApplied>0)s.applicationExperience=clamp(s.applicationExperience+.008*s.applicationCoverage*(1-s.applicationExperience));
  const residueMultiplier=precisionResidueMultiplier(region),decay=1-Math.pow(.70,years);s.residueLoad=Math.max(0,s.residueLoad*(1-decay)+(mineralApplied*(.055+.09*s.applicationCoverage)+syntheticApplied*(.16+.22*s.syntheticCoverage)+selectiveApplied*(.045+.055*s.selectiveCoverage))*residueMultiplier);s.ecologicalPressure=clamp(s.residueLoad/Math.max(1,cultivatedHa(region)/180)*.18,0,.48);s.toxicityPressure=clamp(s.toxicityPressure*Math.exp(-.20*years)+(syntheticApplied/Math.max(1,annual)*.22+selectiveApplied/Math.max(1,annual)*.045)*residueMultiplier,0,.55);return mineralApplied+syntheticApplied+selectiveApplied;
}

export function pesticideControlForCategory(region,category){return clamp(ensureAgriculturalPesticides(region).controlByCategory?.[category]||0,0,MAX_TOTAL_CONTROL);}
export function tickAgriculturalPesticides(region,elapsedDays=7){const s=ensureAgriculturalPesticides(region),tech=region.unlockedTechIds||new Set();s.lastProduced=0;s.lastSyntheticProduced=0;s.lastSelectiveProduced=0;s.lastApplied=0;s.lastSyntheticApplied=0;s.lastSelectiveApplied=0;s.sulfurUsed=0;s.copperUsed=0;s.petroleumFeedstockUsed=0;if(tech.has(CHEMICAL_PEST_CONTROL_TECH_ID)){const annual=annualFullTreatmentDemand(region);if(tech.has(SELECTIVE_PESTICIDES_TECH_ID)){const stock=nonNegative(region.stockpile?.selective_pesticide),target=annual*.20;produceSelectivePesticide(region,Math.max(0,target-stock),elapsedDays);}if(tech.has(SYNTHETIC_PESTICIDES_TECH_ID)){const stock=nonNegative(region.stockpile?.synthetic_pesticide),target=annual*(tech.has(SELECTIVE_PESTICIDES_TECH_ID)?.08:RESERVE_YEARS);produceSyntheticPesticide(region,Math.max(0,target-stock),elapsedDays);}const stock=nonNegative(region.stockpile?.pesticide),target=annual*(tech.has(SYNTHETIC_PESTICIDES_TECH_ID)?.06:RESERVE_YEARS);producePesticide(region,Math.max(0,target-stock),elapsedDays);}applyPesticides(region,elapsedDays);s.productionCapability=Math.max(pesticideProductionCapability(region),syntheticProductionCapability(region),selectiveProductionCapability(region));region.report||={};region.report.agriculturalPesticides={workers:0,produced:s.lastProduced,syntheticProduced:s.lastSyntheticProduced,selectiveProduced:s.lastSelectiveProduced,applied:s.lastApplied,syntheticApplied:s.lastSyntheticApplied,selectiveApplied:s.lastSelectiveApplied,applicationCoverage:s.applicationCoverage,syntheticCoverage:s.syntheticCoverage,selectiveCoverage:s.selectiveCoverage,ipmEffectiveness:s.ipmEffectiveness,chemicalDemandReduction:s.chemicalDemandReduction,ipmControlByCategory:{...s.ipmControlByCategory},controlByCategory:{...s.controlByCategory},resistance:s.resistance,syntheticResistance:s.syntheticResistance,selectiveResistance:s.selectiveResistance,residueLoad:s.residueLoad,ecologicalPressure:s.ecologicalPressure,toxicityPressure:s.toxicityPressure,productionCapability:s.productionCapability,sulfurUsed:s.sulfurUsed,copperUsed:s.copperUsed,petroleumFeedstockUsed:s.petroleumFeedstockUsed};return s;}
function contactCount(region,byId,techId){const ids=new Set([...(region.neighbors||[]),...(region.tradePartnerIds||[])]);if(region.recentTradePartners instanceof Map)for(const id of region.recentTradePartners.keys())ids.add(id);return [...ids].filter(id=>byId.get(id)?.unlockedTechIds?.has?.(techId)).length;}
export function pesticideBreakthroughChances(region,byId){const tech=region.unlockedTechIds||new Set(),industry=industrialReadiness(region),pressure=clamp(outbreakSignal(region)+Number(region.agriculturalPests?.monocultureRisk||0)*.35),sulfur=nonNegative(region.stockpile?.sulfur),copper=nonNegative(region.stockpile?.copper),inputs=clamp((Math.log1p(sulfur)+Math.log1p(copper))/10),hasFactory=nonNegative(region.industrialPlants?.factoryCapacity)>0,firstDiff=1-Math.pow(1-.00018,contactCount(region,byId,CHEMICAL_PEST_CONTROL_TECH_ID)),first=tech.has(CHEMICAL_PEST_CONTROL_TECH_ID)||!hasFactory||industry<.12||inputs<.05?0:clamp(industry*(.42+.23*inputs+.35*pressure)*.000007+firstDiff*(.30+.70*industry)),petrol=nonNegative(region.stockpile?.petrol),petroleum=clamp(Math.log1p(petrol)/6),s=ensureAgriculturalPesticides(region),resistance=clamp(s.resistance),synthDiff=1-Math.pow(1-.00012,contactCount(region,byId,SYNTHETIC_PESTICIDES_TECH_ID)),synthetic=tech.has(SYNTHETIC_PESTICIDES_TECH_ID)||!tech.has(CHEMICAL_PEST_CONTROL_TECH_ID)||!tech.has(PETROLEUM_CRACKING_TECH_ID)||industry<.28||petroleum<.06?0:clamp(industry*(.30+.18*petroleum+.24*pressure+.28*resistance)*.0000045+synthDiff*(.25+.75*industry)),management=managementReadiness(region),chemicalStress=clamp(s.ecologicalPressure+s.toxicityPressure*.8+s.syntheticResistance*.45),ipmDiff=1-Math.pow(1-.00014,contactCount(region,byId,INTEGRATED_PEST_MANAGEMENT_TECH_ID)),ipm=tech.has(INTEGRATED_PEST_MANAGEMENT_TECH_ID)||!tech.has(CHEMICAL_PEST_CONTROL_TECH_ID)||management<.18?0:clamp(management*(.30+.25*pressure+.25*chemicalStress+.20*cropDiversity(region))*.000005+ipmDiff*(.30+.70*management)),selectiveDiff=1-Math.pow(1-.00010,contactCount(region,byId,SELECTIVE_PESTICIDES_TECH_ID)),selective=tech.has(SELECTIVE_PESTICIDES_TECH_ID)||!tech.has(SYNTHETIC_PESTICIDES_TECH_ID)||!tech.has(INTEGRATED_PEST_MANAGEMENT_TECH_ID)||!tech.has(PETROLEUM_CRACKING_TECH_ID)||industry<.34?0:clamp(industry*(.24+.18*management+.24*s.syntheticResistance+.20*chemicalStress+.14*petroleum)*.0000038+selectiveDiff*(.22+.78*industry));return {first,synthetic,ipm,selective};}
export function pesticideBreakthroughChance(region,byId){return pesticideBreakthroughChances(region,byId).first;}
