import { createInfrastructureAsset, evaluateForeignInvestment, foreignMarketAccess } from './infrastructureInvestment.js';
import { ensureCorporateCapitalState } from './corporateCapital.js';
import { infrastructureCapacity } from '../military/infrastructureDamage.js';

const clamp=(v,lo=0,hi=1)=>Math.max(lo,Math.min(hi,Number(v)||0));
const DAYS_PER_YEAR=365.2425;
export const CORPORATE_INFRASTRUCTURE_TYPES=Object.freeze({
 port:{name:'Commercial port',sector:'infrastructure',strategic:true,coastal:true,capitalCost:180,annualRevenue:24,constructionYears:4,materials:{stone:900,wood:500,steel:80},maintenance:{steel:4,wood:8}},
 canal:{name:'Commercial canal',sector:'infrastructure',strategic:true,capitalCost:260,annualRevenue:30,constructionYears:7,materials:{stone:1800,wood:700,steel:110},maintenance:{steel:5,stone:15}},
 mine:{name:'Industrial mine',sector:'mining',strategic:false,capitalCost:120,annualRevenue:20,constructionYears:3,materials:{wood:500,steel:70,machine_components:15},maintenance:{steel:5,machine_components:1},requiresDeposit:true},
 steelworks:{name:'Steelworks',sector:'manufacture',strategic:true,capitalCost:240,annualRevenue:34,constructionYears:5,materials:{stone:800,iron:180,machine_components:30},maintenance:{steel:5,machine_components:2},operation:{iron:90,coal:55}},
 factory:{name:'Industrial factory',sector:'manufacture',strategic:false,capitalCost:150,annualRevenue:23,constructionYears:3,materials:{stone:300,wood:250,steel:90,machine_components:20},maintenance:{steel:3,machine_components:2}},
 telegraph:{name:'Telegraph network',sector:'infrastructure',strategic:true,capitalCost:95,annualRevenue:14,constructionYears:2,materials:{wood:350,copper:45,steel:20},maintenance:{copper:2,wood:5}},
 power_generation:{name:'Power station',sector:'infrastructure',strategic:true,capitalCost:260,annualRevenue:38,constructionYears:5,materials:{stone:500,steel:150,copper:45,machine_components:35},maintenance:{steel:5,machine_components:3},operation:{coal:100}},
 power_grid:{name:'Electricity grid',sector:'infrastructure',strategic:true,capitalCost:190,annualRevenue:28,constructionYears:4,materials:{steel:80,copper:100,wood:300},maintenance:{copper:4,steel:3}},
 water_supply:{name:'Urban water utility',sector:'infrastructure',strategic:false,capitalCost:170,annualRevenue:22,constructionYears:4,materials:{stone:700,steel:70,machine_components:15},maintenance:{steel:3,machine_components:1}},
});
function inventory(region,key){if(key==='steel'||key==='machine_components')return Math.max(0,region.industrialSupply?.inventory?.[key]||0);return Math.max(0,region.stockpile?.[key]??region.resources?.[key]??0);}
function take(region,key,amount){let left=Math.max(0,amount);if(key==='steel'||key==='machine_components'){region.industrialSupply||={};region.industrialSupply.inventory||={};const have=Math.max(0,region.industrialSupply.inventory[key]||0),used=Math.min(have,left);region.industrialSupply.inventory[key]=have-used;left-=used;}if(left>0){region.stockpile||={};const have=Math.max(0,region.stockpile[key]||0),used=Math.min(have,left);region.stockpile[key]=have-used;left-=used;}return amount-left;}
export function ensureCorporateInfrastructure(region){region.corporateInfrastructure||={nextAssetId:1,assets:[],proposals:[]};return region.corporateInfrastructure;}
export function infrastructureTypeAvailable(type,region){const def=CORPORATE_INFRASTRUCTURE_TYPES[type];if(!def)return false;if(def.coastal&&!region.isCoastal)return false;if(def.requiresDeposit&&!Object.keys(region.resourceDeposits||{}).some(k=>k!=='stone'))return false;return true;}
export function eligibleInfrastructureFirms(regions,type){const def=CORPORATE_INFRASTRUCTURE_TYPES[type];if(!def)return[];const out=[];for(const region of regions||[]){const state=ensureCorporateCapitalState(region);for(const firm of state.firms||[])if(firm.status==='active'&&(firm.sector===def.sector||firm.sector==='infrastructure'))out.push({firm,region,polityId:region.governance?.sovereignPolityId||region.polityId});}return out.sort((a,b)=>(b.firm.capitalIndex||0)-(a.firm.capitalIndex||0));}
export function proposeCorporateInfrastructure({type,hostRegion,hostPolity,investorRegion,investorPolity,firm,relation=0,atWar=false,partner=false,warLossRate=0,civilDisorder=0,assetDamageRate=0,concessionYears=30}){const def=CORPORATE_INFRASTRUCTURE_TYPES[type];if(!def||!infrastructureTypeAvailable(type,hostRegion))return{accepted:false,reason:'site_unsuitable'};const foreign=investorPolity?.id!==hostPolity?.id;if(foreign&&!foreignMarketAccess({hostPolity,investorPolity,strategic:def.strategic,relation,atWar,partner}))return{accepted:false,reason:'market_closed'};const capitalStrength=clamp((firm?.capitalIndex||0)/Math.max(1,def.capitalCost*.02));const expectedAnnualProfit=def.annualRevenue*(.55+capitalStrength*.45);const decision=foreign?evaluateForeignInvestment({hostPolity,investorPolity,expectedAnnualProfit,capitalCost:def.capitalCost,strategic:def.strategic,relation,atWar,partner,warLossRate,civilDisorder,assetDamageRate}):{invest:capitalStrength>.08,score:capitalStrength,risk:0,reason:'domestic'};if(!decision.invest)return{accepted:false,reason:decision.reason,decision};const state=ensureCorporateInfrastructure(hostRegion),id=`${hostRegion.id}:corpinfra:${state.nextAssetId++}`,asset={...createInfrastructureAsset({id,type,regionId:hostRegion.id,hostPolityId:hostPolity.id,ownerPolityId:investorPolity.id,operatorPolityId:investorPolity.id,foreignOwner:foreign,strategic:def.strategic,value:def.capitalCost,condition:1,concessionYears:foreign?concessionYears:0}),ownerFirmId:firm?.id||null,builderFirmId:firm?.id||null,status:'construction',progress:0,materialsRequired:{...def.materials},materialsDelivered:{},baseCapacity:1,annualRevenue:def.annualRevenue,constructionYears:def.constructionYears};state.assets.push(asset);if(firm){firm.infrastructureAssets||=[];firm.infrastructureAssets.push(asset.id);firm.capitalIndex=Math.max(.01,(firm.capitalIndex||0)-def.capitalCost*.0015);}return{accepted:true,asset,decision};}
export function tickCorporateInfrastructureAsset(asset,region,elapsedDays=30){const def=CORPORATE_INFRASTRUCTURE_TYPES[asset.type];if(!def)return asset;const years=Math.max(0,elapsedDays)/DAYS_PER_YEAR;if(asset.status==='construction'){let coverage=1;for(const[k,total]of Object.entries(def.materials)){const delivered=asset.materialsDelivered[k]||0,remaining=Math.max(0,total-delivered),wanted=Math.min(remaining,total*years/Math.max(.5,def.constructionYears)*1.5),got=take(region,k,wanted);asset.materialsDelivered[k]=delivered+got;coverage=Math.min(coverage,total?asset.materialsDelivered[k]/total:1);}asset.progress=clamp(Math.min(coverage,asset.progress+years/def.constructionYears));if(asset.progress>=.999){asset.progress=1;asset.status='operational';}return asset;}if(asset.status==='destroyed')return asset;let operating=1;for(const[k,annual]of Object.entries(def.operation||{})){const need=annual*years,got=take(region,k,need);operating=Math.min(operating,need?got/need:1);}let maintained=1;for(const[k,annual]of Object.entries(def.maintenance||{})){const need=annual*years,got=take(region,k,need);maintained=Math.min(maintained,need?got/need:1);}asset.condition=clamp((asset.condition??1)+years*(maintained*.02-(1-maintained)*.12));asset.effectiveCapacity=asset.baseCapacity*operating*infrastructureCapacity(asset);asset.lastOperatingRatio=operating;asset.lastMaintenanceRatio=maintained;return asset;}
export function repairCorporateInfrastructure(asset,region,repairShare=.1){const def=CORPORATE_INFRASTRUCTURE_TYPES[asset.type];if(!def||asset.status==='destroyed'&&asset.condition<=0)return{repaired:0};const desired=Math.min(clamp(repairShare),1-(asset.condition??1));if(desired<=0)return{repaired:0};let coverage=1;for(const[k,total]of Object.entries(def.materials)){const need=total*desired*.35,got=take(region,k,need);coverage=Math.min(coverage,need?got/need:1);}const repaired=desired*coverage;asset.condition=clamp((asset.condition??1)+repaired);asset.status=asset.condition<.35?'crippled':asset.condition<.7?'damaged':'operational';return{repaired};}
