import { createInfrastructureAsset, evaluateForeignInvestment, foreignMarketAccess } from './infrastructureInvestment.js';
import { ensureEconomicOwnershipPolicy, investmentAccess, ownershipSectorForInfrastructureType, stateEnterpriseById } from './economicOwnership.js';
import { infrastructureCapacity } from '../military/infrastructureDamage.js';
const clamp=(v,lo=0,hi=1)=>Math.max(lo,Math.min(hi,Number(v)||0));const DAYS_PER_YEAR=365.2425;
export const CORPORATE_INFRASTRUCTURE_TYPES=Object.freeze({
 port:{name:'Commercial port',sector:'infrastructure',strategic:true,coastal:true,breakthrough:'modern_port_engineering',capitalCost:180,annualRevenue:24,constructionYears:4,materials:{stone:900,wood:500,steel:80},maintenance:{steel:4,wood:8}},
 canal:{name:'Commercial canal',sector:'infrastructure',strategic:true,breakthrough:'canal_engineering',capitalCost:260,annualRevenue:30,constructionYears:7,materials:{stone:1800,wood:700,steel:110},maintenance:{steel:5,stone:15}},
 mine:{name:'Industrial mine',sector:'mining',strategic:false,breakthrough:'industrial_mining',capitalCost:120,annualRevenue:20,constructionYears:3,materials:{wood:500,steel:70,machine_components:15},maintenance:{steel:5,machine_components:1},requiresDeposit:true},
 steelworks:{name:'Steelworks',sector:'manufacture',strategic:true,breakthrough:'steelmaking',capitalCost:240,annualRevenue:34,constructionYears:5,materials:{stone:800,iron:180,machine_components:30},maintenance:{steel:5,machine_components:2},operation:{iron:90,coal:55}},
 factory:{name:'Industrial factory',sector:'manufacture',strategic:false,breakthrough:'factory_system',capitalCost:150,annualRevenue:23,constructionYears:3,materials:{stone:300,wood:250,steel:90,machine_components:20},maintenance:{steel:3,machine_components:2}},
 telegraph:{name:'Telegraph network',sector:'infrastructure',strategic:true,breakthrough:'telegraphy',capitalCost:95,annualRevenue:14,constructionYears:2,materials:{wood:350,copper:45,steel:20},maintenance:{copper:2,wood:5}},
 power_generation:{name:'Power station',sector:'infrastructure',strategic:true,breakthrough:'electrical_generation',capitalCost:260,annualRevenue:38,constructionYears:5,materials:{stone:500,steel:150,copper:45,machine_components:35},maintenance:{steel:5,machine_components:3},operation:{coal:100}},
 power_grid:{name:'Electricity grid',sector:'infrastructure',strategic:true,breakthrough:'electrical_grid',capitalCost:190,annualRevenue:28,constructionYears:4,materials:{steel:80,copper:100,wood:300},maintenance:{copper:4,steel:3}},
 water_supply:{name:'Urban water utility',sector:'infrastructure',strategic:false,breakthrough:'industrial_waterworks',capitalCost:170,annualRevenue:22,constructionYears:4,materials:{stone:700,steel:70,machine_components:15},maintenance:{steel:3,machine_components:1}},
});
function hasKnowledge(region,id){for(const source of [region?.breakthroughs,region?.technologies,region?.tech?.breakthroughs,region?.tech?.known]){if(source instanceof Set&&source.has(id))return true;if(Array.isArray(source)&&source.includes(id))return true;if(source&&typeof source==='object'&&source[id])return true;}const cap=region?.industrialSupply?.capability||{};if(id==='steelmaking'&&(cap.steelmaking||0)>.35)return true;if(['factory_system','industrial_mining','modern_port_engineering','canal_engineering','industrial_waterworks'].includes(id)&&(cap.precision_machining||0)>.45&&(cap.steelmaking||0)>.35)return true;return false;}
function take(region,key,amount){let left=Math.max(0,amount);if(key==='steel'||key==='machine_components'){region.industrialSupply||={};region.industrialSupply.inventory||={};const have=Math.max(0,region.industrialSupply.inventory[key]||0),used=Math.min(have,left);region.industrialSupply.inventory[key]=have-used;left-=used;}if(left>0){region.stockpile||={};const have=Math.max(0,region.stockpile[key]||0),used=Math.min(have,left);region.stockpile[key]=have-used;left-=used;}return amount-left;}
export function ensureCorporateInfrastructure(region){region.corporateInfrastructure||={};const state=region.corporateInfrastructure;state.nextAssetId=Number.isFinite(state.nextAssetId)?state.nextAssetId:1;state.nextProposalId=Number.isFinite(state.nextProposalId)?state.nextProposalId:1;if(!Array.isArray(state.assets))state.assets=[];if(!Array.isArray(state.proposals))state.proposals=[];return state;}
export function infrastructureTypeAvailable(type,hostRegion,supplierRegion=hostRegion){const def=CORPORATE_INFRASTRUCTURE_TYPES[type];if(!def)return false;if(def.coastal&&!hostRegion.isCoastal)return false;if(def.requiresDeposit&&!Object.keys(hostRegion.resourceDeposits||{}).some(k=>k!=='stone'))return false;return hasKnowledge(supplierRegion,def.breakthrough);}
export function eligibleInfrastructureFirms(regions,type){const def=CORPORATE_INFRASTRUCTURE_TYPES[type];if(!def)return[];const out=[];for(const region of regions||[]){const firms=region.corporateCapital?.firms||[];for(const firm of firms)if(firm.status==='active'&&(firm.sector===def.sector||firm.sector==='infrastructure')&&hasKnowledge(region,def.breakthrough))out.push({firm,region,polityId:region.governance?.sovereignPolityId||region.polityId});}return out.sort((a,b)=>(b.firm.capitalIndex||0)-(a.firm.capitalIndex||0));}
export function assessCorporateInfrastructureProposal({type,hostRegion,hostPolity,investorRegion,investorPolity,firm,relation=0,atWar=false,partner=false,warLossRate=0,civilDisorder=0,assetDamageRate=0}){const def=CORPORATE_INFRASTRUCTURE_TYPES[type];if(!def||!infrastructureTypeAvailable(type,hostRegion,investorRegion))return{viable:false,reason:'missing_expertise_or_site'};const foreign=investorPolity?.id!==hostPolity?.id,ownershipSector=ownershipSectorForInfrastructureType(type),access=investmentAccess(hostPolity,ownershipSector,{foreign,proposedStateShare:0,proposedForeignShare:foreign?1:0});if(!access.allowed)return{viable:false,reason:access.reason,access,ownershipSector};if(foreign&&!foreignMarketAccess({hostPolity,investorPolity,strategic:def.strategic,relation,atWar,partner}))return{viable:false,reason:'market_closed'};const capitalStrength=clamp((firm?.capitalIndex||0)/Math.max(1,def.capitalCost*.02)),expectedAnnualProfit=def.annualRevenue*(.55+capitalStrength*.45),decision=foreign?evaluateForeignInvestment({hostPolity,investorPolity,expectedAnnualProfit,capitalCost:def.capitalCost,strategic:def.strategic,relation,atWar,partner,warLossRate,civilDisorder,assetDamageRate}):{invest:capitalStrength>.08,score:capitalStrength,risk:0,reason:'domestic'};if(!decision.invest)return{viable:false,reason:decision.reason,decision,foreign,expectedAnnualProfit,capitalStrength};return{viable:true,foreign,def,decision,expectedAnnualProfit,capitalStrength};}
export function createCorporateInfrastructureOffer({type,hostRegion,hostPolity,investorRegion,investorPolity,firm,relation=0,atWar=false,partner=false,warLossRate=0,civilDisorder=0,assetDamageRate=0,concessionYears=30,currentTick=0,expiresAfterWeeks=104}){const assessment=assessCorporateInfrastructureProposal({type,hostRegion,hostPolity,investorRegion,investorPolity,firm,relation,atWar,partner,warLossRate,civilDisorder,assetDamageRate});if(!assessment.viable||!assessment.foreign)return{created:false,reason:assessment.reason||'not_foreign',assessment};const state=ensureCorporateInfrastructure(hostRegion);for(const proposal of state.proposals)if(proposal.status==='pending'&&proposal.type===type&&proposal.investorPolityId===investorPolity.id&&proposal.firmId===(firm?.id||null))return{created:false,reason:'duplicate_pending_offer',proposal,assessment};const def=assessment.def;const id=`${hostRegion.id}:corpinfra-offer:${state.nextProposalId++}`;const proposal={id,type,hostRegionId:hostRegion.id,hostPolityId:hostPolity.id,investorRegionId:investorRegion.id,investorPolityId:investorPolity.id,firmId:firm?.id||null,status:'pending',createdTick:currentTick,expiresTick:currentTick+Math.max(13,expiresAfterWeeks),concessionYears:Math.max(5,Math.round(concessionYears)),capitalCost:def.capitalCost,constructionYears:def.constructionYears,annualRevenue:def.annualRevenue,materials:{...def.materials},strategic:!!def.strategic,breakthrough:def.breakthrough,expectedAnnualProfit:assessment.expectedAnnualProfit,risk:assessment.decision?.risk||0,score:assessment.decision?.score||0,hostCapitalContribution:0,investorCapitalContribution:def.capitalCost,ownership:'foreign_concession',operator:'investor'};state.proposals.push(proposal);return{created:true,proposal,assessment};}
export function expireCorporateInfrastructureOffers(region,currentTick=0){const state=ensureCorporateInfrastructure(region);let expired=0;for(const proposal of state.proposals){if(proposal.status==='pending'&&Number.isFinite(proposal.expiresTick)&&proposal.expiresTick<=currentTick){proposal.status='expired';proposal.resolvedTick=currentTick;expired++;}}return expired;}
export function proposeCorporateInfrastructure({type,hostRegion,hostPolity,investorRegion,investorPolity,firm,relation=0,atWar=false,partner=false,warLossRate=0,civilDisorder=0,assetDamageRate=0,concessionYears=30}){const assessment=assessCorporateInfrastructureProposal({type,hostRegion,hostPolity,investorRegion,investorPolity,firm,relation,atWar,partner,warLossRate,civilDisorder,assetDamageRate});if(!assessment.viable)return{accepted:false,reason:assessment.reason,decision:assessment.decision};const {def,foreign,decision}=assessment;const state=ensureCorporateInfrastructure(hostRegion),id=`${hostRegion.id}:corpinfra:${state.nextAssetId++}`,asset={...createInfrastructureAsset({id,type,regionId:hostRegion.id,hostPolityId:hostPolity.id,ownerPolityId:investorPolity.id,operatorPolityId:investorPolity.id,foreignOwner:foreign,strategic:def.strategic,value:def.capitalCost,condition:1,concessionYears:foreign?concessionYears:0}),ownerFirmId:firm?.id||null,builderFirmId:firm?.id||null,status:'construction',progress:0,materialsRequired:{...def.materials},materialsDelivered:{},baseCapacity:1,annualRevenue:def.annualRevenue,constructionYears:def.constructionYears,technologySourcePolityId:investorPolity.id,financedByPolityId:investorPolity.id,builtByPolityId:investorPolity.id};state.assets.push(asset);if(firm){firm.infrastructureAssets||=[];firm.infrastructureAssets.push(asset.id);firm.capitalIndex=Math.max(.01,(firm.capitalIndex||0)-def.capitalCost*.0015);}if(foreign){hostRegion.industrialSupply||={};hostRegion.industrialSupply.exposure||={};hostRegion.industrialSupply.exposure[def.breakthrough]=clamp((hostRegion.industrialSupply.exposure[def.breakthrough]||0)+.04);}return{accepted:true,asset,decision};}
export function resolveCorporateInfrastructureOffer({offerId,hostRegion,hostPolity,regions,polities,choice='reject',currentTick=0}){const state=ensureCorporateInfrastructure(hostRegion),offer=state.proposals.find(p=>p.id===offerId);if(!offer||offer.status!=='pending')return{accepted:false,reason:'offer_not_pending',offer};if(choice!=='accept'){offer.status='rejected';offer.resolvedTick=currentTick;return{accepted:false,rejected:true,offer};}const investorRegion=(regions||[]).find(r=>r.id===offer.investorRegionId),investorPolity=(polities||[]).find(p=>p.id===offer.investorPolityId),firm=investorRegion?.corporateCapital?.firms?.find(f=>f.id===offer.firmId);if(!investorRegion||!investorPolity||!firm||firm.status!=='active'){offer.status='withdrawn';offer.resolvedTick=currentTick;return{accepted:false,reason:'investor_unavailable',offer};}const result=proposeCorporateInfrastructure({type:offer.type,hostRegion,hostPolity,investorRegion,investorPolity,firm,concessionYears:offer.concessionYears});offer.status=result.accepted?'accepted':'withdrawn';offer.resolvedTick=currentTick;offer.assetId=result.asset?.id||null;offer.resolutionReason=result.reason||null;return{...result,offer};}
export function tickCorporateInfrastructureAsset(asset,region,elapsedDays=30){const def=CORPORATE_INFRASTRUCTURE_TYPES[asset.type];if(!def)return asset;const years=Math.max(0,elapsedDays)/DAYS_PER_YEAR;if(asset.status==='construction'){let coverage=1;for(const[k,total]of Object.entries(def.materials)){const delivered=asset.materialsDelivered[k]||0,remaining=Math.max(0,total-delivered),wanted=Math.min(remaining,total*years/Math.max(.5,def.constructionYears)*1.5),got=take(region,k,wanted);asset.materialsDelivered[k]=delivered+got;coverage=Math.min(coverage,total?asset.materialsDelivered[k]/total:1);}asset.progress=clamp(Math.min(coverage,asset.progress+years/def.constructionYears));if(asset.progress>=.999){asset.progress=1;asset.status='operational';}return asset;}if(asset.status==='destroyed')return asset;let operating=1;for(const[k,annual]of Object.entries(def.operation||{})){const need=annual*years,got=take(region,k,need);operating=Math.min(operating,need?got/need:1);}let maintained=1;for(const[k,annual]of Object.entries(def.maintenance||{})){const need=annual*years,got=take(region,k,need);maintained=Math.min(maintained,need?got/need:1);}asset.condition=clamp((asset.condition??1)+years*(maintained*.02-(1-maintained)*.12));asset.effectiveCapacity=asset.baseCapacity*operating*infrastructureCapacity(asset);asset.lastOperatingRatio=operating;asset.lastMaintenanceRatio=maintained;return asset;}
export function repairCorporateInfrastructure(asset,region,repairShare=.1){const def=CORPORATE_INFRASTRUCTURE_TYPES[asset.type];if(!def||asset.status==='destroyed'&&asset.condition<=0)return{repaired:0};const desired=Math.min(clamp(repairShare),1-(asset.condition??1));if(desired<=0)return{repaired:0};let coverage=1;for(const[k,total]of Object.entries(def.materials)){const need=total*desired*.35,got=take(region,k,need);coverage=Math.min(coverage,need?got/need:1);}const repaired=desired*coverage;asset.condition=clamp((asset.condition??1)+repaired);asset.status=asset.condition<.35?'crippled':asset.condition<.7?'damaged':'operational';return{repaired};}


export function buildStateEnterpriseInfrastructure({type,hostRegion,hostPolity,enterpriseId,currentTick=0}){
  const def=CORPORATE_INFRASTRUCTURE_TYPES[type];
  if(!def)return{accepted:false,reason:'unknown_infrastructure_type'};
  const enterprise=stateEnterpriseById(hostPolity,enterpriseId);
  if(!enterprise||enterprise.status!=='active')return{accepted:false,reason:'enterprise_not_found'};
  const sector=ownershipSectorForInfrastructureType(type);
  if(!enterprise.sectors.includes(sector)&&!enterprise.sectors.includes('infrastructure'))return{accepted:false,reason:'outside_enterprise_mandate',sector};
  if(!infrastructureTypeAvailable(type,hostRegion,hostRegion))return{accepted:false,reason:'missing_expertise_or_site'};
  const access=investmentAccess(hostPolity,sector,{foreign:false,proposedStateShare:enterprise.stateOwnership,proposedForeignShare:0});
  if(!access.allowed)return{accepted:false,reason:access.reason,access,sector};
  const capitalCost=Math.max(0,def.capitalCost||0);
  if((enterprise.governmentCapital||0)<capitalCost)return{accepted:false,reason:'insufficient_enterprise_capital',required:capitalCost,available:enterprise.governmentCapital||0};
  const state=ensureCorporateInfrastructure(hostRegion),id=`${hostRegion.id}:stateinfra:${state.nextAssetId++}`;
  enterprise.governmentCapital-=capitalCost;
  const asset={...createInfrastructureAsset({id,type,regionId:hostRegion.id,hostPolityId:hostPolity.id,ownerPolityId:hostPolity.id,operatorPolityId:hostPolity.id,foreignOwner:false,strategic:def.strategic,value:capitalCost,condition:1,concessionYears:0}),ownerStateEnterpriseId:enterprise.id,builderStateEnterpriseId:enterprise.id,stateOwnership:enterprise.stateOwnership,status:'construction',progress:0,materialsRequired:{...def.materials},materialsDelivered:{},baseCapacity:1,annualRevenue:def.annualRevenue,constructionYears:def.constructionYears,technologySourcePolityId:hostPolity.id,financedByPolityId:hostPolity.id,builtByPolityId:hostPolity.id,publicServiceObligation:enterprise.serviceObligation,profitTarget:enterprise.profitTarget,commercialIndependence:enterprise.commercialIndependence,createdTick:currentTick};
  state.assets.push(asset);
  enterprise.assets||=[];
  enterprise.assets.push(asset.id);
  enterprise.investedCapital=(enterprise.investedCapital||0)+capitalCost;
  return{accepted:true,asset,enterprise,sector,capitalCost};
}
