import { ensureAgriculturalGenetics } from './agriculturalGenetics.js?v=20260921-genetics1';
import { cropBreedingCapability } from './cropBreeding.js?v=20260921-breeding1';

const DAYS_PER_YEAR=365.2425;
const PLANT_FOODS=Object.freeze(['staple_grains','pulses','fruit_vegetables']);
const TRAITS=Object.freeze(['pestResistance','droughtTolerance','heatTolerance','biofortification','yieldStability']);
const clamp=(v,lo=0,hi=1)=>Math.max(lo,Math.min(hi,Number(v)||0));
const positive=v=>Math.max(0,Number(v)||0);

function literacy(region){return clamp(region?.publicEducation?.literacy??region?.education?.literacyRate??region?.massEducation?.literacyRate??region?.educationLevel??0);}
function electricity(region){return clamp(region?.electricity?.industrialService||0);}
function computing(region){const c=region?.computingIndustry||{},cap=c.capacity||{},exp=c.experience||{},stock=region?.stockpile||{};return clamp(clamp(Math.log1p(positive(stock.computers))/4)*.25+clamp(positive(cap.chip_design)/16)*.20+clamp(positive(cap.wafer_fab)/16)*.20+clamp(positive(exp.chip_design))*.20+clamp(positive(exp.wafer_fab))*.15);}
function laboratory(region){const research=clamp(region?.medicalProgress?.researchCapability??region?.research?.capability??region?.technology?.researchCapability??0);const machining=clamp(region?.industrialSupply?.capability?.precision_machining||0);return clamp(research*.55+machining*.20+literacy(region)*.25);}
function normaliseFocus(focus={}){const raw={};let total=0;for(const t of TRAITS){raw[t]=Math.max(0,Number(focus[t])||0);total+=raw[t];}if(total<=0){Object.assign(raw,{pestResistance:.24,droughtTolerance:.22,heatTolerance:.18,biofortification:.18,yieldStability:.18});total=1;}for(const t of TRAITS)raw[t]/=total;return raw;}

export function ensureCropBiotechnology(region){region.cropBiotechnology||={};const s=region.cropBiotechnology;s.traits||={};s.adoptionByCategory||={};for(const c of PLANT_FOODS){s.traits[c]||={};for(const t of TRAITS)if(!Number.isFinite(s.traits[c][t]))s.traits[c][t]=0;if(!Number.isFinite(s.adoptionByCategory[c]))s.adoptionByCategory[c]=0;}for(const [k,v] of Object.entries({investment:.35,capability:0,platformMaturity:0,commercialSeedShare:0,seedDependence:0,localSeedAutonomy:1,diversityCost:0,electricityLoad:0,aggregateAdoption:0}))if(!Number.isFinite(s[k]))s[k]=v;s.focus=normaliseFocus(s.focus);return s;}
export function setCropBiotechnologyPolicy(region,patch={}){const s=ensureCropBiotechnology(region);if(patch.investment!==undefined)s.investment=clamp(patch.investment);if(patch.focus)s.focus=normaliseFocus(patch.focus);return {investment:s.investment,focus:{...s.focus}};}
export function cropBiotechnologyCapability(region){const s=ensureCropBiotechnology(region),power=electricity(region),digital=computing(region),labs=laboratory(region),breeding=cropBreedingCapability(region);if(power<.35||digital<.18||labs<.28||breeding<.35){s.capability=0;return 0;}s.capability=clamp(power*.18+digital*.25+labs*.34+breeding*.23);return s.capability;}

export function tickCropBiotechnology(region,elapsedDays=7){const s=ensureCropBiotechnology(region),g=ensureAgriculturalGenetics(region),years=Math.max(0,Number(elapsedDays)||0)/DAYS_PER_YEAR,capability=cropBiotechnologyCapability(region),investment=clamp(s.investment),focus=normaliseFocus(s.focus);const maturityTarget=capability*investment;const maturityAdjust=1-Math.exp(-years*(.08+.22*investment));s.platformMaturity=clamp(s.platformMaturity+(maturityTarget-s.platformMaturity)*maturityAdjust);let adoptionSum=0,diversityCost=0;for(const category of PLANT_FOODS){const traits=s.traits[category],geneticBase=clamp((g.preservedDiversity?.[category]||0)*.55+(g.liveDiversity?.[category]||0)*.45);const annualGain=(.001+capability*.010)*(.2+investment*.8)*(.35+geneticBase*.65);for(const trait of TRAITS)traits[trait]=clamp(traits[trait]+(1-traits[trait])*annualGain*focus[trait]*years,0,.72);const targetAdoption=clamp(s.platformMaturity*(.35+.65*capability));const adoptionAdjust=1-Math.exp(-years*(.10+.28*investment));s.adoptionByCategory[category]=clamp(s.adoptionByCategory[category]+(targetAdoption-s.adoptionByCategory[category])*adoptionAdjust);const adoption=s.adoptionByCategory[category];const narrow=adoption*capability*.0035*years;if(g.liveDiversity)g.liveDiversity[category]=clamp((g.liveDiversity[category]||.5)-narrow,.08,1);diversityCost+=narrow;adoptionSum+=adoption;}s.aggregateAdoption=adoptionSum/PLANT_FOODS.length;s.commercialSeedShare=clamp(s.aggregateAdoption*(.35+.45*investment));const bank=clamp(g.seedBankCapability||0),localCapability=clamp(capability*.65+bank*.35);s.seedDependence=clamp(s.commercialSeedShare*(1-localCapability*.55));s.localSeedAutonomy=clamp(1-s.seedDependence);s.diversityCost=diversityCost/PLANT_FOODS.length;s.electricityLoad=s.platformMaturity*(.03+.08*capability)*Math.max(0,Number(elapsedDays)||0)/7;region.report||={};region.report.cropBiotechnology=cropBiotechnologySummary(region);return s;}

export function biotechnologyPestProtection(region,category){if(!PLANT_FOODS.includes(category))return 0;const s=ensureCropBiotechnology(region);return clamp((s.traits[category]?.pestResistance||0)*(s.adoptionByCategory[category]||0)*.34,0,.24);}
export function biotechnologyClimateRelief(region,category){if(!PLANT_FOODS.includes(category))return 0;const s=ensureCropBiotechnology(region),t=s.traits[category],adopt=clamp(s.adoptionByCategory[category]||0),rain=Number(region?.climate?.rainfallMultiplier??1),evap=Number(region?.climate?.evaporationMultiplier??1),heat=Math.max(0,Number(region?.climate?.temperatureAnomalyC)||0),dry=clamp(Math.max(0,1-rain)*.8+Math.max(0,evap-1)*.35),heatStress=clamp(heat/4);return clamp(adopt*(t.droughtTolerance*dry*.22+t.heatTolerance*heatStress*.20+t.yieldStability*Math.max(dry,heatStress)*.12),0,.24);}
export function biotechnologyNutritionMultiplier(region,category){if(!PLANT_FOODS.includes(category))return 1;const s=ensureCropBiotechnology(region);return 1+clamp((s.traits[category]?.biofortification||0)*(s.adoptionByCategory[category]||0)*.10,0,.08);}
export function cropBiotechnologySummary(region){const s=ensureCropBiotechnology(region);return {workers:0,investment:s.investment,capability:cropBiotechnologyCapability(region),platformMaturity:s.platformMaturity,aggregateAdoption:s.aggregateAdoption,adoptionByCategory:{...s.adoptionByCategory},traits:Object.fromEntries(PLANT_FOODS.map(c=>[c,{...s.traits[c]}])),commercialSeedShare:s.commercialSeedShare,seedDependence:s.seedDependence,localSeedAutonomy:s.localSeedAutonomy,diversityCost:s.diversityCost,electricityLoad:s.electricityLoad,focus:{...s.focus}};}
