import { ensureAgriculturalGenetics } from './agriculturalGenetics.js?v=20260921-genetics1';

const DAYS_PER_YEAR=365.2425;
const PLANT_FOODS=Object.freeze(['staple_grains','pulses','fruit_vegetables']);
const TRAITS=Object.freeze(['yield','droughtTolerance','heatTolerance','pestResistance','shortSeason']);
const clamp=(v,lo=0,hi=1)=>Math.max(lo,Math.min(hi,Number(v)||0));

function literacy(region){return clamp(region?.publicEducation?.literacy??region?.education?.literacyRate??region?.massEducation?.literacyRate??region?.educationLevel??0);}
function stateCapacity(region){return clamp(region?.militaryFinance?.stateCapacity??region?.governance?.administrativeControl??.3);}
function recordKeeping(region){const tech=region?.unlockedTechIds||new Set();return clamp((tech.has?.('writing')?.22:0));}
function normaliseFocus(focus={}){const raw={yield:Math.max(0,Number(focus.yield)||0),droughtTolerance:Math.max(0,Number(focus.droughtTolerance)||0),heatTolerance:Math.max(0,Number(focus.heatTolerance)||0),pestResistance:Math.max(0,Number(focus.pestResistance)||0),shortSeason:Math.max(0,Number(focus.shortSeason)||0)};let total=TRAITS.reduce((n,k)=>n+raw[k],0);if(total<=0){raw.yield=.35;raw.droughtTolerance=.2;raw.heatTolerance=.15;raw.pestResistance=.2;raw.shortSeason=.1;total=1;}for(const key of TRAITS)raw[key]/=total;return raw;}

export function ensureCropBreeding(region){region.cropBreeding||={};const s=region.cropBreeding;s.traits||={};s.progress||={};s.selectionCost||={};for(const category of PLANT_FOODS){s.traits[category]||={};s.progress[category]||={};for(const trait of TRAITS){if(!Number.isFinite(s.traits[category][trait]))s.traits[category][trait]=0;if(!Number.isFinite(s.progress[category][trait]))s.progress[category][trait]=0;}if(!Number.isFinite(s.selectionCost[category]))s.selectionCost[category]=0;}if(!Number.isFinite(s.selectionIntensity))s.selectionIntensity=.18;s.focus=normaliseFocus(s.focus);s.categoryFocus||={};if(!Number.isFinite(s.capability))s.capability=.12;if(!Number.isFinite(s.aggregateImprovement))s.aggregateImprovement=0;return s;}
export function setCropBreedingPolicy(region,patch={}){const s=ensureCropBreeding(region);if(patch.selectionIntensity!==undefined)s.selectionIntensity=clamp(patch.selectionIntensity);if(patch.focus)s.focus=normaliseFocus(patch.focus);if(patch.category&&patch.categoryFocus&&PLANT_FOODS.includes(patch.category))s.categoryFocus[patch.category]=normaliseFocus(patch.categoryFocus);return {selectionIntensity:s.selectionIntensity,focus:{...s.focus},categoryFocus:{...s.categoryFocus}};}
export function cropBreedingCapability(region){const s=ensureCropBreeding(region),genetics=ensureAgriculturalGenetics(region),records=recordKeeping(region),literacySignal=literacy(region),admin=stateCapacity(region),seedKnowledge=clamp((genetics.aggregateDiversity||.5)*.45+(genetics.aggregateReserve||.4)*.25+(genetics.seedBankCapability||0)*.30);s.capability=clamp(.10+records*.26+literacySignal*.22+admin*.14+seedKnowledge*.28);return s.capability;}
export function tickCropBreeding(region,elapsedDays=7){const s=ensureCropBreeding(region),g=ensureAgriculturalGenetics(region),years=Math.max(0,Number(elapsedDays)||0)/DAYS_PER_YEAR,capability=cropBreedingCapability(region),intensity=clamp(s.selectionIntensity);let aggregate=0;for(const category of PLANT_FOODS){const focus=normaliseFocus(s.categoryFocus[category]||s.focus),live=clamp(g.liveDiversity?.[category]||0),preserved=clamp(g.preservedDiversity?.[category]||0),geneticInput=clamp(live*.68+preserved*.32),traits=s.traits[category];const annualProgress=(.0025+capability*.0125)*(.25+intensity*.75)*(.35+geneticInput*.65);for(const trait of TRAITS){const headroom=Math.max(0,1-traits[trait]);const gain=headroom*annualProgress*focus[trait]*years;traits[trait]=clamp(traits[trait]+gain,0,.8);s.progress[category][trait]=gain;}const concentration=Math.max(...TRAITS.map(t=>focus[t]));const selectionLoss=live*(.0012+concentration*.0048)*Math.pow(intensity,1.35)*(.55+capability*.45)*years;if(g.liveDiversity)g.liveDiversity[category]=clamp(live-selectionLoss,.08,1);if(g.geneticErosion)g.geneticErosion[category]=clamp(1-g.liveDiversity[category]);s.selectionCost[category]=selectionLoss;aggregate+=TRAITS.reduce((n,t)=>n+traits[t],0)/TRAITS.length;}s.aggregateImprovement=aggregate/PLANT_FOODS.length;region.report||={};region.report.cropBreeding=cropBreedingSummary(region);return region.report.cropBreeding;}
export function breedingYieldMultiplier(region,category){if(!PLANT_FOODS.includes(category))return 1;const t=ensureCropBreeding(region).traits[category];const latitude=Math.abs(Number(region?.centroid?.[1])||0),seasonPressure=clamp((latitude-42)/30);return 1+t.yield*.16+t.shortSeason*seasonPressure*.07;}
export function breedingPestProtection(region,category){if(!PLANT_FOODS.includes(category))return 0;return clamp(ensureCropBreeding(region).traits[category].pestResistance*.24,0,.20);}
export function breedingClimateRelief(region,category){if(!PLANT_FOODS.includes(category))return 0;const t=ensureCropBreeding(region).traits[category],rain=Number(region?.climate?.rainfallMultiplier??1),evap=Number(region?.climate?.evaporationMultiplier??1),heat=Math.max(0,Number(region?.climate?.temperatureAnomalyC)||0),dry=clamp(Math.max(0,1-rain)*.8+Math.max(0,evap-1)*.35),heatStress=clamp(heat/4);return clamp(t.droughtTolerance*dry*.18+t.heatTolerance*heatStress*.16,0,.20);}
export function cropBreedingSummary(region){const s=ensureCropBreeding(region);return {workers:0,selectionIntensity:s.selectionIntensity,focus:{...s.focus},categoryFocus:{...s.categoryFocus},capability:cropBreedingCapability(region),traits:Object.fromEntries(PLANT_FOODS.map(id=>[id,{...s.traits[id]}])),progress:Object.fromEntries(PLANT_FOODS.map(id=>[id,{...s.progress[id]}])),selectionCost:{...s.selectionCost},aggregateImprovement:s.aggregateImprovement};}
