import { economicOwnershipIndicators, ensureEconomicOwnershipPolicy } from './economicOwnership.js';
const clamp=(v,lo=0,hi=1)=>Math.max(lo,Math.min(hi,Number(v)||0));
export const FOREIGN_INVESTMENT_POLICIES=Object.freeze({OPEN:'open',SCREENED:'screened',PARTNERS:'partners_only',DOMESTIC_PREFERENCE:'domestic_preference',DOMESTIC_ONLY:'domestic_only'});
export function ensureInvestmentPolicy(polity){polity.foreignInvestmentPolicy||={general:FOREIGN_INVESTMENT_POLICIES.OPEN,strategic:FOREIGN_INVESTMENT_POLICIES.SCREENED};polity.investmentReputation??=1;polity.expropriationMemory??=0;return polity.foreignInvestmentPolicy;}
export function setForeignInvestmentPolicy(polity,{general,strategic}={}){const p=ensureInvestmentPolicy(polity);if(Object.values(FOREIGN_INVESTMENT_POLICIES).includes(general))p.general=general;if(Object.values(FOREIGN_INVESTMENT_POLICIES).includes(strategic))p.strategic=strategic;return p;}
export function foreignMarketAccess({hostPolity,investorPolity,strategic=false,relation=0,atWar=false,partner=false}){const p=ensureInvestmentPolicy(hostPolity)[strategic?'strategic':'general'];if(atWar||p===FOREIGN_INVESTMENT_POLICIES.DOMESTIC_ONLY)return false;if(p===FOREIGN_INVESTMENT_POLICIES.PARTNERS)return partner;if(p===FOREIGN_INVESTMENT_POLICIES.SCREENED&&relation<-.2)return false;return relation>-.75;}
export function investmentRisk({hostPolity,warLossRate=0,civilDisorder=0,assetDamageRate=0}){ensureInvestmentPolicy(hostPolity);const ownership=economicOwnershipIndicators(hostPolity);return clamp(warLossRate*.32+civilDisorder*.24+assetDamageRate*.16+(1-hostPolity.investmentReputation)*.3+hostPolity.expropriationMemory*.2+(1-ownership.policyPredictability)*.2+(1-ownership.contractReliability)*.24+ownership.nationalisationMemory*.28);}
export function scoreForeignInvestment({expectedAnnualProfit,capitalCost,risk,relation=0,strategic=false}){const annualReturn=Math.max(0,expectedAnnualProfit)/Math.max(1,capitalCost);return annualReturn*3.2-risk*1.35+relation*.12-(strategic?.08:0);}
export function evaluateForeignInvestment({hostPolity,investorPolity,expectedAnnualProfit,capitalCost,strategic=false,relation=0,atWar=false,partner=false,warLossRate=0,civilDisorder=0,assetDamageRate=0,minScore=.08}){if(!foreignMarketAccess({hostPolity,investorPolity,strategic,relation,atWar,partner}))return {invest:false,reason:'market_closed',score:-Infinity,risk:1};const risk=investmentRisk({hostPolity,warLossRate,civilDisorder,assetDamageRate}),score=scoreForeignInvestment({expectedAnnualProfit,capitalCost,risk,relation,strategic});return {invest:score>=minScore,reason:score>=minScore?'profitable':'risk_adjusted_return_too_low',score,risk};}
export function chooseNpcInvestmentPolicy(polity,{securityThreat=0,foreignDependence=0,industrialAmbition=0,capitalShortage=0,hostility=0}={}){const strategicClosure=clamp(securityThreat*.55+foreignDependence*.25+hostility*.35),openness=clamp(capitalShortage*.5+(1-industrialAmbition)*.25-securityThreat*.25);const strategic=strategicClosure>.7?FOREIGN_INVESTMENT_POLICIES.DOMESTIC_ONLY:strategicClosure>.42?FOREIGN_INVESTMENT_POLICIES.PARTNERS:FOREIGN_INVESTMENT_POLICIES.SCREENED;const general=openness>.55?FOREIGN_INVESTMENT_POLICIES.OPEN:industrialAmbition>.65?FOREIGN_INVESTMENT_POLICIES.DOMESTIC_PREFERENCE:FOREIGN_INVESTMENT_POLICIES.SCREENED;return setForeignInvestmentPolicy(polity,{general,strategic});}
export function createInfrastructureAsset({id,type,regionId,hostPolityId,ownerPolityId=hostPolityId,operatorPolityId=ownerPolityId,foreignOwner=false,strategic=false,value=1,condition=1,concessionYears=0}){return{id,type,regionId,hostPolityId,ownerPolityId,operatorPolityId,foreignOwner,strategic,value:Math.max(0,value),condition:clamp(condition),concessionYearsRemaining:Math.max(0,concessionYears),status:'operational'};}
export function nationaliseAsset({asset,hostPolity,ownerPolity,compensationShare=0}){const previousOwner=asset.ownerPolityId,compensation=clamp(compensationShare);asset.ownerPolityId=hostPolity.id;asset.operatorPolityId=hostPolity.id;asset.foreignOwner=false;asset.concessionYearsRemaining=0;ensureInvestmentPolicy(hostPolity);const ownership=ensureEconomicOwnershipPolicy(hostPolity);hostPolity.expropriationMemory=clamp(hostPolity.expropriationMemory+(1-compensation)*.45+.08);hostPolity.investmentReputation=clamp(hostPolity.investmentReputation-(1-compensation)*.38-.05);ownership.nationalisationMemory=clamp(ownership.nationalisationMemory+(1-compensation)*.38+.06);ownership.policyPredictability=clamp(ownership.policyPredictability-(1-compensation)*.16-.025);ownership.contractReliability=clamp(ownership.contractReliability-(1-compensation)*.2-.03);if(ownerPolity){ownerPolity.foreignClaims||={};ownerPolity.foreignClaims[hostPolity.id]=(ownerPolity.foreignClaims[hostPolity.id]||0)+asset.value*(1-compensation);ownerPolity.diplomaticGrievances||={};ownerPolity.diplomaticGrievances[hostPolity.id]=(ownerPolity.diplomaticGrievances[hostPolity.id]||0)+(1-compensation)*.5+.08;}return{previousOwner,compensationDue:asset.value*compensation,uncompensatedClaim:asset.value*(1-compensation)};}
export function tickInvestmentReputation(polity,elapsedYears){ensureInvestmentPolicy(polity);const ownership=ensureEconomicOwnershipPolicy(polity),y=Math.max(0,elapsedYears);polity.expropriationMemory=Math.max(0,polity.expropriationMemory-y*.012);polity.investmentReputation=clamp(polity.investmentReputation+(1-polity.investmentReputation)*Math.min(.04*y,.2));ownership.nationalisationMemory=Math.max(0,ownership.nationalisationMemory-y*.01);ownership.policyPredictability=clamp(ownership.policyPredictability+(1-ownership.policyPredictability)*Math.min(.012*y,.08));ownership.contractReliability=clamp(ownership.contractReliability+(1-ownership.contractReliability)*Math.min(.01*y,.06));}
