const clamp=(v,lo=0,hi=1)=>Math.max(lo,Math.min(hi,Number(v)||0));
export const FOREIGN_INVESTMENT_POLICIES=Object.freeze({OPEN:'open',SCREENED:'screened',PARTNERS:'partners_only',DOMESTIC_PREFERENCE:'domestic_preference',DOMESTIC_ONLY:'domestic_only'});
export function ensureInvestmentPolicy(polity){ polity.foreignInvestmentPolicy||={general:FOREIGN_INVESTMENT_POLICIES.OPEN,strategic:FOREIGN_INVESTMENT_POLICIES.SCREENED}; polity.investmentReputation??=1; polity.expropriationMemory??=0; return polity.foreignInvestmentPolicy; }
export function foreignMarketAccess({hostPolity,investorPolity,strategic=false,relation=0,atWar=false,partner=false}){ const p=ensureInvestmentPolicy(hostPolity)[strategic?'strategic':'general']; if(atWar||p===FOREIGN_INVESTMENT_POLICIES.DOMESTIC_ONLY)return false; if(p===FOREIGN_INVESTMENT_POLICIES.PARTNERS)return partner; if(p===FOREIGN_INVESTMENT_POLICIES.SCREENED&&relation<-.2)return false; return relation>-.75; }
export function investmentRisk({hostPolity,warLossRate=0,civilDisorder=0,assetDamageRate=0}){ ensureInvestmentPolicy(hostPolity); return clamp(warLossRate*.38+civilDisorder*.28+assetDamageRate*.18+(1-hostPolity.investmentReputation)*.46+hostPolity.expropriationMemory*.32); }
export function scoreForeignInvestment({expectedAnnualProfit,capitalCost,risk,relation=0,strategic=false}){ const annualReturn=Math.max(0,expectedAnnualProfit)/Math.max(1,capitalCost); return annualReturn*3.2-risk*1.35+relation*.12-(strategic?.08:0); }
export function createInfrastructureAsset({id,type,regionId,hostPolityId,ownerPolityId=hostPolityId,operatorPolityId=ownerPolityId,foreignOwner=false,strategic=false,value=1,condition=1,concessionYears=0}){ return {id,type,regionId,hostPolityId,ownerPolityId,operatorPolityId,foreignOwner,strategic,value:Math.max(0,value),condition:clamp(condition),concessionYearsRemaining:Math.max(0,concessionYears),status:'operational'}; }
export function nationaliseAsset({asset,hostPolity,ownerPolity,compensationShare=0}){ const previousOwner=asset.ownerPolityId; const compensation=clamp(compensationShare); asset.ownerPolityId=hostPolity.id; asset.operatorPolityId=hostPolity.id; asset.foreignOwner=false; asset.concessionYearsRemaining=0; ensureInvestmentPolicy(hostPolity); hostPolity.expropriationMemory=clamp(hostPolity.expropriationMemory+(1-compensation)*.45+.08); hostPolity.investmentReputation=clamp(hostPolity.investmentReputation-(1-compensation)*.38-.05); if(ownerPolity){ ownerPolity.foreignClaims||={}; ownerPolity.foreignClaims[hostPolity.id]=(ownerPolity.foreignClaims[hostPolity.id]||0)+asset.value*(1-compensation); ownerPolity.diplomaticGrievances||={}; ownerPolity.diplomaticGrievances[hostPolity.id]=(ownerPolity.diplomaticGrievances[hostPolity.id]||0)+(1-compensation)*.5+.08; } return {previousOwner,compensationDue:asset.value*compensation,uncompensatedClaim:asset.value*(1-compensation)}; }
export function tickInvestmentReputation(polity,elapsedYears){ ensureInvestmentPolicy(polity); const y=Math.max(0,elapsedYears); polity.expropriationMemory=Math.max(0,polity.expropriationMemory-y*.012); polity.investmentReputation=clamp(polity.investmentReputation+(1-polity.investmentReputation)*Math.min(.04*y,.2)); }
