import { ensureIndustrialSupply, chooseInfrastructureSupplier, applyForeignSupplierExposure, applyDomesticSupplierExperience, ensureProcurementPolicy } from './industrialSupply.js?v=20260915-industrial2';
import { createInfrastructureAsset } from './infrastructureInvestment.js';
import { infrastructureCapacity } from '../military/infrastructureDamage.js';

const DAYS_PER_YEAR = 365.2425;
const clamp = (v, lo = 0, hi = 1) => Math.max(lo, Math.min(hi, Number(v) || 0));
export const RAILWAY_REQUIREMENTS_PER_100KM = Object.freeze({ steel: 260, machine_components: 12, rail_stock: 18, steam_locomotive: 3 });
export function ensureRailwayState(polity) { polity.railways ||= { nextLineId: 1, lines: [] }; if (!Array.isArray(polity.railways.lines)) polity.railways.lines=[]; if(!Number.isFinite(polity.railways.nextLineId)) polity.railways.nextLineId=1; return polity.railways; }
export function planRailway({ polity, fromRegion, toRegion, lengthKm, domesticRegions=[], foreignOffers=[], concessionYears=0 }) {
 const km=Math.max(1,Number(lengthKm)||1), scale=km/100; const requirements=Object.fromEntries(Object.entries(RAILWAY_REQUIREMENTS_PER_100KM).map(([k,v])=>[k,v*scale]));
 const supplier=chooseInfrastructureSupplier({polity,domesticRegions,foreignOffers,requirements,strategic:true}); if(!supplier||supplier.capability<=.02)return {feasible:false,reason:'no_capable_supplier',requirements};
 const state=ensureRailwayState(polity), foreign=!!supplier.foreign, concession=foreign?Math.max(0,concessionYears||supplier.concessionYears||0):0, procurementPolicy=ensureProcurementPolicy(polity).infrastructure;
 const line={...createInfrastructureAsset({id:`${polity.id||'polity'}:rail:${state.nextLineId++}`,type:'railway',regionId:fromRegion.id,hostPolityId:polity.id,ownerPolityId:foreign?(supplier.polityId||polity.id):polity.id,operatorPolityId:foreign?(supplier.polityId||polity.id):polity.id,foreignOwner:foreign,strategic:true,value:km,condition:1,concessionYears:concession}),fromRegionId:fromRegion.id,toRegionId:toRegion.id,lengthKm:km,status:'construction',progress:0,requirements,supplierRegionId:supplier.region.id,supplierPolityId:supplier.polityId||null,foreignSupplier:foreign,procurementPolicy,supplierCapabilityAtAward:supplier.capability,concessionYears:concession,hostOwnershipShare:foreign&&concession?0:1,coalRequiredPerYear:km*.18,steelMaintenancePerYear:km*.045,capacity:0,utilisation:0};
 state.lines.push(line); if(foreign){applyForeignSupplierExposure(fromRegion,supplier.region,.6);applyForeignSupplierExposure(toRegion,supplier.region,.6);}else{applyDomesticSupplierExperience(fromRegion,supplier.region,.5);applyDomesticSupplierExperience(toRegion,supplier.region,.5);} return {feasible:true,line,supplier};
}
export function tickRailwayConstruction(line,hostRegions,supplierRegion,elapsedDays=7){if(line.status!=='construction')return line;const years=Math.max(0,elapsedDays)/DAYS_PER_YEAR,s=ensureIndustrialSupply(supplierRegion),cap=clamp((s.capability.railway_engineering||0)*.45+(s.capability.steelmaking||0)*.2+(s.capability.locomotive_engineering||0)*.2+(s.capability.precision_machining||0)*.15),constructionYears=Math.max(2,11-cap*8);line.progress=clamp(line.progress+years/constructionYears);if(line.foreignSupplier)for(const r of hostRegions)applyForeignSupplierExposure(r,supplierRegion,years*2);else for(const r of hostRegions)applyDomesticSupplierExperience(r,supplierRegion,years*1.2);if(line.progress>=1){line.status='operational';line.capacity=Math.max(.2,cap);}return line;}
export function tickRailwayOperations(line,hostRegions,elapsedDays=7){if(line.status!=='operational'&&line.status!=='damaged'&&line.status!=='crippled')return line;const years=Math.max(0,elapsedDays)/DAYS_PER_YEAR,coalNeeded=line.coalRequiredPerYear*years*Math.max(.15,line.utilisation||.5),steelNeeded=line.steelMaintenancePerYear*years*(.6+Math.max(.15,line.utilisation||.5)*.8),coal=hostRegions.reduce((s,r)=>s+Math.max(0,r.stockpile?.coal||0),0),steel=hostRegions.reduce((s,r)=>s+Math.max(0,r.industrialSupply?.inventory?.steel||0),0),fuel=clamp(coal/Math.max(.001,coalNeeded)),maint=clamp(steel/Math.max(.001,steelNeeded));line.condition=clamp(line.condition+years*(maint*.025-(1-maint)*.16));line.effectiveCapacity=line.capacity*fuel*infrastructureCapacity(line);line.concessionYearsRemaining=Math.max(0,(line.concessionYearsRemaining||0)-years);if(line.foreignSupplier&&line.concessionYears>0&&line.concessionYearsRemaining<=0){line.hostOwnershipShare=1;line.ownerPolityId=line.hostPolityId;line.operatorPolityId=line.hostPolityId;line.foreignOwner=false;}return line;}
export function railwayTransportMultiplier(polity,fromRegionId,toRegionId){const line=ensureRailwayState(polity).lines.find(l=>l.status!=='destroyed'&&l.status!=='construction'&&((l.fromRegionId===fromRegionId&&l.toRegionId===toRegionId)||(l.fromRegionId===toRegionId&&l.toRegionId===fromRegionId)));if(!line)return 1;return 1+Math.max(0,line.effectiveCapacity??line.capacity*infrastructureCapacity(line)??0)*2.4;}
