const DAYS_PER_YEAR = 365.2425;
const clamp = (v, lo = 0, hi = 1) => Math.max(lo, Math.min(hi, Number(v) || 0));
const nonNegative = (v) => Math.max(0, Number(v) || 0);

function polityId(region) { return region?.governance?.sovereignPolityId || region?.polityId || region?.id || null; }
function warSides(war) { const attackers=new Set([...(war?.attackerPolityIds||[]),war?.attackerPolityId,war?.attackerId].filter(Boolean)); const defenders=new Set([...(war?.defenderPolityIds||[]),war?.defenderPolityId,war?.defenderId].filter(Boolean)); return {attackers,defenders}; }
function sideRegions(regions,ids){return (regions||[]).filter(region=>ids.has(polityId(region))||ids.has(region.id));}
function nuclearRegions(regions){return regions.filter(region=>region.nuclearRisk?.nuclearPower&&region.nuclearRisk?.destructiveCapacity>0);}
function sideCapability(regions){const nuclear=nuclearRegions(regions);if(!nuclear.length)return null;const destructiveCapacity=clamp(nuclear.reduce((s,r)=>s+nonNegative(r.nuclearRisk?.destructiveCapacity),0)/Math.max(1,nuclear.length));const secureSecondStrike=clamp(nuclear.reduce((s,r)=>s+nonNegative(r.nuclearRisk?.secureSecondStrike),0)/nuclear.length);const annualRisk=clamp(Math.max(...nuclear.map(r=>nonNegative(r.nuclearRisk?.annualCatastrophicExchangeRisk))));const periodRisk=clamp(Math.max(...nuclear.map(r=>nonNegative(r.nuclearRisk?.periodExchangeProbability))));return{nuclear,destructiveCapacity,secureSecondStrike,annualRisk,periodRisk};}
function exchangeScale(initiator,responder,rng){const pressure=clamp(Math.max(initiator.annualRisk,responder.annualRisk)),retaliation=clamp(responder.secureSecondStrike*responder.destructiveCapacity),draw=clamp(rng?.()??Math.random());if(pressure<.02&&draw>.25)return'limited';if(pressure<.06&&draw>.45)return'regional';return retaliation>.35?'major':'regional';}
function populationOf(region){const d=region?.demographics;if(d&&[d.children,d.workingAge,d.elderly].every(Number.isFinite))return Math.max(0,d.children+d.workingAge+d.elderly);return Math.max(0,Number(region?.population)||0);}
function applyDeaths(region,fraction){const loss=clamp(fraction,0,.9),d=region.demographics;if(d){for(const key of['children','workingAge','elderly'])if(Number.isFinite(d[key]))d[key]=Math.max(0,d[key]*(1-loss));region.population=Math.max(0,(d.children||0)+(d.workingAge||0)+(d.elderly||0));}else if(Number.isFinite(region.population))region.population=Math.max(0,region.population*(1-loss));}
function impactWeight(region,totalPopulation){const populationShare=totalPopulation>0?populationOf(region)/totalPopulation:1,urbanisation=clamp(region.urbanisation?.share??region.urbanShare??region.settlements?.urbanShare??.25),infrastructure=clamp(region.infrastructure?.development??region.infrastructureLevel??.35);return clamp(.45*populationShare+.35*urbanisation+.20*infrastructure,.05,1);}
function baseConsequences(scale){if(scale==='limited')return{direct:.025,infrastructure:.08,fallout:.15,soot:.05};if(scale==='regional')return{direct:.09,infrastructure:.24,fallout:.38,soot:.18};return{direct:.22,infrastructure:.48,fallout:.70,soot:.42};}
function applySideEffects(regions,scale,forceFraction,exchangeId){if(!regions.length)return{deaths:0,populationBefore:0};const totalPopulation=regions.reduce((s,r)=>s+populationOf(r),0),consequence=baseConsequences(scale);let deaths=0;for(const region of regions){const before=populationOf(region),weight=impactWeight(region,totalPopulation),directFraction=clamp(consequence.direct*forceFraction*(.35+.65*weight),0,.55);applyDeaths(region,directFraction);deaths+=Math.max(0,before-populationOf(region));region.nuclearAftermath||={};region.nuclearAftermath.exchangeId=exchangeId;region.nuclearAftermath.infrastructureDamage=clamp(Math.max(region.nuclearAftermath.infrastructureDamage||0,consequence.infrastructure*forceFraction*(.45+.55*weight)));region.nuclearAftermath.fallout=clamp(Math.max(region.nuclearAftermath.fallout||0,consequence.fallout*forceFraction*(.55+.45*weight)));region.nuclearAftermath.sootExposure=clamp(Math.max(region.nuclearAftermath.sootExposure||0,consequence.soot*forceFraction));region.nuclearAftermath.foodSystemShock=clamp(Math.max(region.nuclearAftermath.foodSystemShock||0,consequence.soot*.8+consequence.infrastructure*.35));region.nuclearAftermath.lastScale=scale;region.stability=clamp((region.stability??.5)-directFraction*.8-region.nuclearAftermath.infrastructureDamage*.18);region.report||={};region.report.nuclearAftermath=nuclearAftermathSummary(region);}return{deaths,populationBefore:totalPopulation};}
function consumeWarheads(regions,fraction){const f=clamp(fraction);for(const region of regions){const forces=region.nuclearForces,weapons=region.nuclearWeapons;if(forces?.operationalWarheads>0)forces.operationalWarheads=Math.max(0,Math.round(forces.operationalWarheads*(1-f)));if(forces?.reserveWarheads>0)forces.reserveWarheads=Math.max(0,Math.round(forces.reserveWarheads*(1-f*.35)));if(weapons?.operationalWarheads>0)weapons.operationalWarheads=Math.max(0,Math.round(weapons.operationalWarheads*(1-f)));}}

export function resolveNuclearExchange(regions,war,currentTick=0,rng=Math.random){const{attackers,defenders}=warSides(war),attackerRegions=sideRegions(regions,attackers),defenderRegions=sideRegions(regions,defenders),attacker=sideCapability(attackerRegions),defender=sideCapability(defenderRegions);if(!attacker||!defender)return null;const attackerTrigger=clamp(attacker.periodRisk||attacker.annualRisk/52),defenderTrigger=clamp(defender.periodRisk||defender.annualRisk/52),initiatorIsAttacker=attackerTrigger>=defenderTrigger,trigger=Math.max(attackerTrigger,defenderTrigger);if((rng?.()??Math.random())>=trigger)return null;const initiator=initiatorIsAttacker?attacker:defender,responder=initiatorIsAttacker?defender:attacker,initiatorRegions=initiatorIsAttacker?attackerRegions:defenderRegions,responderRegions=initiatorIsAttacker?defenderRegions:attackerRegions,scale=exchangeScale(initiator,responder,rng),initialForceFraction=scale==='limited'?.08:scale==='regional'?.28:.62,retaliationFraction=clamp(initialForceFraction*(.25+.75*responder.secureSecondStrike),0,.8),exchangeId=`nuclear-${currentTick}-${polityId(initiatorRegions[0])}-${polityId(responderRegions[0])}`;const responderLosses=applySideEffects(responderRegions,scale,initialForceFraction*initiator.destructiveCapacity,exchangeId),initiatorLosses=applySideEffects(initiatorRegions,scale,retaliationFraction*responder.destructiveCapacity,exchangeId);consumeWarheads(initiatorRegions,initialForceFraction);consumeWarheads(responderRegions,retaliationFraction);const globalSootShock=clamp(baseConsequences(scale).soot*(initialForceFraction*initiator.destructiveCapacity+retaliationFraction*responder.destructiveCapacity));for(const region of regions||[]){region.nuclearAftermath||={};region.nuclearAftermath.globalSootShock=clamp(Math.max(region.nuclearAftermath.globalSootShock||0,globalSootShock));region.nuclearAftermath.foodSystemShock=clamp(Math.max(region.nuclearAftermath.foodSystemShock||0,globalSootShock*.7));region.report||={};region.report.nuclearAftermath=nuclearAftermathSummary(region);}return{type:'nuclear_exchange',exchangeId,tick:currentTick,scale,initiatorPolityId:polityId(initiatorRegions[0]),responderPolityId:polityId(responderRegions[0]),initialForceFraction,retaliationFraction,globalSootShock,estimatedDirectDeaths:Math.round(responderLosses.deaths+initiatorLosses.deaths),title:'Nuclear weapons used',message:`A ${scale} nuclear exchange has occurred. Surviving retaliatory forces and cascading infrastructure, fallout and food-system damage will continue to shape the crisis.`};}

export function tickNuclearAftermath(regions,elapsedDays=7){const years=Math.max(0,Number(elapsedDays)||0)/DAYS_PER_YEAR;for(const region of regions||[]){const a=region.nuclearAftermath;if(!a)continue;const fallout=clamp(a.fallout||0),soot=clamp(Math.max(a.sootExposure||0,a.globalSootShock||0)),foodShock=clamp(a.foodSystemShock||0),annualMortality=clamp(fallout*.035+soot*.012,0,.12);if(annualMortality>0&&years>0)applyDeaths(region,1-Math.pow(1-annualMortality,years));region.stability=clamp((region.stability??.5)-(fallout*.025+foodShock*.02)*years);const decay=Math.pow(.5,years/1.5);a.fallout=clamp(fallout*decay);a.sootExposure=clamp((a.sootExposure||0)*Math.pow(.5,years/2.5));a.globalSootShock=clamp((a.globalSootShock||0)*Math.pow(.5,years/3));a.foodSystemShock=clamp(foodShock*Math.pow(.5,years/2));a.infrastructureDamage=clamp((a.infrastructureDamage||0)*Math.pow(.5,years/8));region.report||={};region.report.nuclearAftermath=nuclearAftermathSummary(region);}}
export function tickNuclearExchange(regions,activeWars=[],currentTick=0,elapsedDays=7,rng=Math.random){tickNuclearAftermath(regions,elapsedDays);const events=[];for(const war of activeWars||[]){if(war?.nuclearExchangeResolved)continue;const event=resolveNuclearExchange(regions,war,currentTick,rng);if(!event)continue;war.nuclearExchangeResolved=true;war.nuclearExchangeId=event.exchangeId;events.push(event);}return events;}
export function nuclearAftermathSummary(region){const a=region.nuclearAftermath||{};return{exchangeId:a.exchangeId||null,infrastructureDamage:clamp(a.infrastructureDamage||0),fallout:clamp(a.fallout||0),sootExposure:clamp(a.sootExposure||0),globalSootShock:clamp(a.globalSootShock||0),foodSystemShock:clamp(a.foodSystemShock||0),lastScale:a.lastScale||null};}
