const pct=v=>`${Math.round(Math.max(0,Math.min(1,Number(v)||0))*100)}%`;
function polityId(r){return r?.governance?.sovereignPolityId||r?.polityId||null;}
function playerRegions(sim){const id=sim?.activePlayerPolityId;return (sim?.regions||[]).filter(r=>polityId(r)===id);}
function aggregate(regions,key){const vals=regions.map(r=>Number(r.industrialInvestment?.last?.[key])||0);return vals.reduce((a,b)=>a+b,0);}
function weighted(regions,fn){let n=0,d=0;for(const r of regions){const w=Math.max(1,r.population||1);n+=(Number(fn(r))||0)*w;d+=w;}return d?n/d:0;}
function render(sim,panel){
  const regions=playerRegions(sim);if(!regions.length){panel.innerHTML='';return;}
  const subsidy=weighted(regions,r=>r.industrialInvestment?.subsidyRate?.motor_vehicle||0);
  const tariff=weighted(regions,r=>r.industrialInvestment?.last?.tariffSupport||0);
  const capacity=aggregate(regions,'factoryCapacity'),mil=aggregate(regions,'militarySpend'),sub=aggregate(regions,'subsidySpend');
  const lines=regions.flatMap(r=>r.industrialPlants?.lines||[]);const active=lines.filter(l=>l.status==='active').length,retool=lines.filter(l=>l.status==='retooling').length,moth=lines.filter(l=>l.status==='mothballed').length;
  panel.innerHTML=`<h3>Industrial capacity & procurement</h3><p class="advisor-voice">“A tariff does not manufacture a tank. It can, however, keep the engine works, machine tools and assembly halls alive until we need them.”</p><div class="advisor-report-row"><span>Factory capacity</span><strong>${capacity.toFixed(1)}</strong></div><div class="advisor-report-row"><span>Production lines</span><strong>${active} active · ${retool} retooling · ${moth} mothballed</strong></div><div class="advisor-report-row"><span>Motor-vehicle tariff support</span><strong>${Math.round(tariff*100)}%</strong></div><div class="advisor-report-row"><span>Recent military procurement</span><strong>${mil.toFixed(2)}</strong></div><div class="advisor-report-row"><span>Recent industrial subsidies</span><strong>${sub.toFixed(2)}</strong></div><label class="advisor-field"><span>Domestic motor-vehicle production subsidy <small>Paid only on actual domestic output. It can preserve civilian capacity but costs the treasury.</small></span><input id="motor-industry-subsidy" type="range" min="0" max="0.5" step="0.05" value="${subsidy}"><strong>${pct(subsidy)}</strong></label><p class="advisor-note">Import tariffs are set through the existing trade-policy controls. Government tank and self-propelled-gun orders rise with mobilisation and war demand, but firms still need components, tooling and time to deliver them.</p>`;
  panel.querySelector('#motor-industry-subsidy')?.addEventListener('change',e=>{const v=Number(e.target.value)||0;for(const r of regions){r.industrialInvestment||={};r.industrialInvestment.subsidyRate||={};r.industrialInvestment.subsidyRate.motor_vehicle=v;}render(sim,panel);});
}
function maybeMount(sim){const content=document.getElementById('advisor-content'),treasurer=document.querySelector('[data-advisor="treasurer"]');if(!content||!treasurer?.classList.contains('active'))return;let p=document.getElementById('industrial-investment-advisor-panel');if(!p){p=document.createElement('section');p.id='industrial-investment-advisor-panel';p.className='advisor-section';content.appendChild(p);}render(sim,p);}
export function installIndustrialInvestmentUi(sim=window.__worldsim){const content=document.getElementById('advisor-content');if(!sim||!content||content.dataset.industrialInvestmentUiInstalled==='true')return false;content.dataset.industrialInvestmentUiInstalled='true';let queued=false;const schedule=()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;maybeMount(sim);});};new MutationObserver(schedule).observe(content,{childList:true,subtree:false});document.getElementById('advisor-tabs')?.addEventListener('click',schedule);document.getElementById('btn-council')?.addEventListener('click',schedule);schedule();return true;}
if(typeof window!=='undefined'&&window.__worldsim)installIndustrialInvestmentUi(window.__worldsim);
