import { MOTION_TYPES, identifyMajorPowers, internationalOrganisationSummary, proposeInternationalOrganisation, submitInternationalMotion, worldInstitutionReadiness } from '../diplomacy/internationalOrganisations.js?v=20260919-global-institutions1';

const pct=v=>`${Math.round((Number(v)||0)*100)}%`;
export function renderInternationalOrganisationControls(container,playerPolity,world,{onAction=null}={}){
  if(!container||!playerPolity)return;const readiness=worldInstitutionReadiness(world.polities,world.regions,world.activeWars||[]);const orgs=(world.internationalOrganisations||[]).filter(o=>o.memberPolityIds.includes(playerPolity.id));const wrap=document.createElement('div');wrap.className='raid-section international-organisations-section';
  const majors=identifyMajorPowers(world.polities,world.regions,Math.min(5,Math.max(2,Math.round(Math.sqrt(world.polities.length||1)))));
  const existing=orgs.map(o=>{const s=internationalOrganisationSummary(o);return `<div class="raid-status"><strong>${s.name}</strong> · ${s.members} members · legitimacy ${pct(s.legitimacy)} · acceptance ${pct(s.acceptance)} · impartiality ${pct(s.impartiality)}${s.hostPolityId===playerPolity.id?' · hosted here':''}<br><label class="control-row">Submit motion<select data-org-motion="${o.id}">${Object.values(MOTION_TYPES).map(m=>`<option value="${m.id}">${m.label}</option>`).join('')}</select></label><button data-submit-motion="${o.id}">Submit motion</button></div>`}).join('');
  wrap.innerHTML=`<strong>International institutions</strong><div class="raid-status">World readiness ${pct(readiness.readiness)} · connectivity ${pct(readiness.connectivity)} · shared demand ${pct(readiness.demand)}</div>${existing||'<div class="raid-status">You are not currently a member of a permanent international organisation.</div>'}<details><summary>Propose new organisation</summary><label class="control-row">Name<input data-org-name value="International Assembly"></label><label class="control-row">Universal membership<select data-org-universal><option value="yes">Yes</option><option value="no">No</option></select></label><label class="control-row">Weighted voting <span data-weight-label>10%</span><input type="range" min="0" max="100" value="10" data-org-weight></label><label class="control-row">Host concentration <span data-host-label>25%</span><input type="range" min="0" max="100" value="25" data-org-host></label><label class="control-row">Major-power permanent seats<select multiple size="${Math.min(5,majors.length)}" data-org-permanent>${majors.map(id=>`<option value="${id}">${world.polities.find(p=>p.id===id)?.name||id}</option>`).join('')}</select></label><label class="control-row">Major-power vetoes<select multiple size="${Math.min(5,majors.length)}" data-org-veto>${majors.map(id=>`<option value="${id}">${world.polities.find(p=>p.id===id)?.name||id}</option>`).join('')}</select></label><button data-propose-org>Propose organisation</button><div class="raid-status" data-org-result></div></details>`;
  const weight=wrap.querySelector('[data-org-weight]'),host=wrap.querySelector('[data-org-host]');weight?.addEventListener('input',()=>wrap.querySelector('[data-weight-label]').textContent=`${weight.value}%`);host?.addEventListener('input',()=>wrap.querySelector('[data-host-label]').textContent=`${host.value}%`);
  wrap.querySelector('[data-propose-org]')?.addEventListener('click',()=>{const selected=sel=>[...wrap.querySelector(sel).selectedOptions].map(o=>o.value);const result=proposeInternationalOrganisation({proposerPolityId:playerPolity.id,name:wrap.querySelector('[data-org-name]').value||'International Organisation',level:'assembly',hostPolityId:playerPolity.id,charter:{universalMembership:wrap.querySelector('[data-org-universal]').value==='yes',weightedVoting:Number(weight.value)/100,hostConcentration:Number(host.value)/100,permanentMemberIds:selected('[data-org-permanent]'),vetoMemberIds:selected('[data-org-veto]')}},world,world.currentTick||0);wrap.querySelector('[data-org-result]').textContent=result.formed?`Formed with ${result.organisation.memberPolityIds.length} members. Legitimacy ${pct(result.organisation.metrics.legitimacy)}; international acceptance ${pct(result.organisation.metrics.acceptance)}.`:`Proposal failed: ${String(result.reason||'insufficient support').replaceAll('_',' ')}.`;onAction?.();});
  wrap.querySelectorAll('[data-submit-motion]').forEach(btn=>btn.addEventListener('click',()=>{const org=world.internationalOrganisations.find(o=>o.id===btn.dataset.submitMotion);const type=wrap.querySelector(`[data-org-motion="${btn.dataset.submitMotion}"]`)?.value;const result=submitInternationalMotion(org,{proposerPolityId:playerPolity.id,type,strength:.6},world,world.currentTick||0);btn.textContent=result.passed?'Motion passed':result.motion?.status==='vetoed'?'Vetoed':'Motion failed';onAction?.();}));container.appendChild(wrap);
}
