from pathlib import Path

p=Path('js/diplomacy/nuclearCrisisBargaining.js')
s=p.read_text()
old="function applyDemandCompliance(complier,other,demand,currentTick){if([CRISIS_DEMAND_TYPES.WITHDRAW_FORWARD_NUCLEAR_ASSETS,CRISIS_DEMAND_TYPES.REMOVE_MISSILES].includes(demand.type)){for(const d of Object.values(ensureNuclearAllianceState(complier).deployments).filter(d=>d.role==='provider'&&d.status==='active'&&(!demand.targetDeploymentId||d.id===demand.targetDeploymentId))){const host=other?.id===d.hostRegionId?other:null;if(host)withdrawAlliedNuclearDeployment(complier,host,d.id,{currentTick});else d.status='withdrawn';}}if(demand.type===CRISIS_DEMAND_TYPES.ACCEPT_INSPECTIONS)for(const t of Object.values(complier.nuclearArmsControl?.treaties||{}))if(t.status==='active')t.terms.inspectionAccess=clamp((t.terms.inspectionAccess||0)+.2);if(demand.type===CRISIS_DEMAND_TYPES.FREEZE_DEPLOYMENTS)ensureNuclearCrisisBargaining(complier).deploymentFreezeUntil=currentTick+180;demand.status='accepted';demand.resolvedTick=currentTick;}"
new="function applyDemandCompliance(complier,other,demand,currentTick,regions=[]){if([CRISIS_DEMAND_TYPES.WITHDRAW_FORWARD_NUCLEAR_ASSETS,CRISIS_DEMAND_TYPES.REMOVE_MISSILES].includes(demand.type)){for(const d of Object.values(ensureNuclearAllianceState(complier).deployments).filter(d=>d.role==='provider'&&d.status==='active'&&(!demand.targetDeploymentId||d.id===demand.targetDeploymentId))){const host=(regions||[]).find(r=>r.id===d.hostRegionId)||(other?.id===d.hostRegionId?other:null);if(host)withdrawAlliedNuclearDeployment(complier,host,d.id,{currentTick});else d.status='withdrawn';}}if(demand.type===CRISIS_DEMAND_TYPES.ACCEPT_INSPECTIONS)for(const t of Object.values(complier.nuclearArmsControl?.treaties||{}))if(t.status==='active')t.terms.inspectionAccess=clamp((t.terms.inspectionAccess||0)+.2);if(demand.type===CRISIS_DEMAND_TYPES.FREEZE_DEPLOYMENTS)ensureNuclearCrisisBargaining(complier).deploymentFreezeUntil=currentTick+180;demand.status='accepted';demand.resolvedTick=currentTick;}"
if old in s:s=s.replace(old,new,1)
old2="export function concludeCrisisSettlement(a,b,caseId,{acceptingRegionId=null,currentTick=null,publicTerms=true}={}){const ac=ensureNuclearCrisisBargaining(a).cases[caseId],bc=ensureNuclearCrisisBargaining(b).cases[caseId];if(!ac||!bc||ac.status!=='open')return{concluded:false,reason:'case_not_open'};const accepting=acceptingRegionId===b.id?b:a,other=accepting===a?b:a,evaluation=evaluateCrisisSettlement(accepting,other,caseId);if(!evaluation.accept)return{concluded:false,reason:'settlement_not_acceptable',evaluation};for(const d of ac.demands.filter(x=>x.recipientRegionId===accepting.id&&x.status==='pending'))applyDemandCompliance(accepting,other,d,currentTick);"
new2="export function concludeCrisisSettlement(a,b,caseId,{acceptingRegionId=null,currentTick=null,publicTerms=true,regions=[]}={}){const ac=ensureNuclearCrisisBargaining(a).cases[caseId],bc=ensureNuclearCrisisBargaining(b).cases[caseId];if(!ac||!bc||ac.status!=='open')return{concluded:false,reason:'case_not_open'};const accepting=acceptingRegionId===b.id?b:a,other=accepting===a?b:a,evaluation=evaluateCrisisSettlement(accepting,other,caseId);if(!evaluation.accept)return{concluded:false,reason:'settlement_not_acceptable',evaluation};for(const d of ac.demands.filter(x=>x.recipientRegionId===accepting.id&&x.status==='pending'))applyDemandCompliance(accepting,other,d,currentTick,regions);"
if old2 in s:s=s.replace(old2,new2,1)
p.write_text(s)
print('crisis bargaining host-resolution patch applied')
