from pathlib import Path
p=Path('js/world/region.js')
s=p.read_text()
old="""export async function loadWorld() {\n  const [geoRes, metaRes, resourcesRes, terrainRes] = await Promise.all([\n    fetch('data/world/regions.geo.json'), fetch('data/world/regions.meta.json'),\n    fetch('data/world/resources.initial.json?v=20260912-silkroad1'),\n    fetch('data/world/terrain.initial.json?v=20260912-silkroad1'),\n  ]);\n  const geo = await geoRes.json(); const meta = await metaRes.json(); const resources = await resourcesRes.json();\n  const terrain = await terrainRes.json();\n  const metaById = new Map(meta.regions.map((r) => [r.id, r]));\n  const regions = geo.features.map((feature) => {\n"""
new="""export async function loadWorld() {\n  const report = (message) => {\n    if (typeof window !== 'undefined' && typeof window.__reportWorldStartup === 'function') {\n      window.__reportWorldStartup(message);\n    }\n    console.info('[land-loader]', message);\n  };\n  const fetchJson = async (url, label) => {\n    const started = typeof performance !== 'undefined' ? performance.now() : Date.now();\n    report(`Land regions · requesting ${label}…`);\n    const response = await fetch(url);\n    const elapsed = ((typeof performance !== 'undefined' ? performance.now() : Date.now()) - started) / 1000;\n    report(`Land regions · ${label} HTTP ${response.status} after ${elapsed.toFixed(1)}s · reading body…`);\n    if (!response.ok) throw new Error(`${label} request failed: HTTP ${response.status}`);\n    const text = await response.text();\n    report(`Land regions · ${label} received ${(text.length / 1024 / 1024).toFixed(1)} MB · parsing JSON…`);\n    const parsed = JSON.parse(text);\n    report(`Land regions · ${label} parsed`);\n    return parsed;\n  };\n\n  const [geo, meta, resources, terrain] = await Promise.all([\n    fetchJson('data/world/regions.geo.json', 'geometry'),\n    fetchJson('data/world/regions.meta.json', 'metadata'),\n    fetchJson('data/world/resources.initial.json?v=20260912-silkroad1', 'resources'),\n    fetchJson('data/world/terrain.initial.json?v=20260912-silkroad1', 'terrain'),\n  ]);\n  const metaById = new Map(meta.regions.map((r) => [r.id, r]));\n  const regions = [];\n  report(`Land regions · constructing ${geo.features.length.toLocaleString()} regions…`);\n  for (let featureIndex = 0; featureIndex < geo.features.length; featureIndex += 1) {\n    const feature = geo.features[featureIndex];\n"""
if old not in s:
    raise SystemExit('loadWorld header anchor not found')
s=s.replace(old,new,1)
old_tail="""    return region;\n  });\n  return regions;\n}\n"""
new_tail="""    regions.push(region);\n    if ((featureIndex + 1) % 100 === 0 && featureIndex + 1 < geo.features.length) {\n      report(`Land regions · constructed ${(featureIndex + 1).toLocaleString()} / ${geo.features.length.toLocaleString()}…`);\n      await new Promise((resolve) => setTimeout(resolve, 0));\n    }\n  }\n  report(`Land regions · constructed ${regions.length.toLocaleString()} regions`);\n  return regions;\n}\n"""
if old_tail not in s:
    raise SystemExit('loadWorld tail anchor not found')
s=s.replace(old_tail,new_tail,1)
p.write_text(s)
