import { AI_GOVERNANCE_MEASURES, conductAiInspection, ensureAiGovernance } from './aiStatecraft.js?v=20260923-ai-statecraft1';
import { recordInformationIncident } from './informationIntegrity.js?v=20260922-info1';
import { recordInternationalCrisisSignal } from './internationalCrisisBridge.js?v=20260920-intl-crisis1';

const clamp=(v,lo=0,hi=1)=>Math.max(lo,Math.min(hi,Number(v)||0));
const polityId=(r)=>r?.governance?.sovereignPolityId||r?.polityId||r?.controllingActorId||r?.id||null;
let nextIncidentId=1;

export const AI_INCIDENT_TYPES=Object.freeze({DECISION_FAILURE:'decision_failure',DATA_POISONING:'data_poisoning',MODEL_COMPROMISE:'model_compromise',AUTHORISED_MISUSE:'authorised_misuse',INFRASTRUCTURE_DISRUPTION:'infrastructure_disruption',FINANCIAL_DISRUPTION:'financial_disruption',INFORMATION_MANIPULATION:'information_manipulation',STRATEGIC_WARNING_ERROR:'strategic_warning_error',MODEL_EXFILTRATION:'model_exfiltration',EVALUATION_EVASION:'evaluation_evasion'});
const SPECS=Object.freeze({
 decision_failure:{domain:'industry',publicVisibility:.28,international:.18},data_poisoning:{domain:'infrastructure',publicVisibility:.24,international:.36},model_compromise:{domain:'information',publicVisibility:.30,international:.52},authorised_misuse:{domain:'politicalPower',publicVisibility:.38,international:.42},infrastructure_disruption:{domain:'infrastructure',publicVisibility:.72,international:.54},financial_disruption:{domain:'economy',publicVisibility:.62,international:.42},information_manipulation:{domain:'information',publicVisibility:.58,international:.48},strategic_warning_error:{domain:'military',publicVisibility:.32,international:.72},model_exfiltration:{domain:'information',publicVisibility:.22,international:.58},evaluation_evasion:{domain:'industry',publicVisibility:.18,international:.34},
});

function regionsOf(world,id){return (world.regions||[]).filter(r=>polityId(r)===id);}
function weighted(rs,fn){let n=0,w=0;for(const r of rs){const p=Math.max(1,Number(r.population)||1);n+=clamp(fn(r))*p;w+=p;}return w?n/w:0;}
function accordsFor(world,id){return (world.aiGovernanceAccords||[]).filter(a=>a.active&&a.memberPolityIds.includes(id));}
function hasMeasure(world,id,m){return accordsFor(world,id).some(a=>a.measures.includes(m));}
function aiCapability(r){return clamp(r.aiLabour?.capability??r.aiEconomy?.capability??0);}

export function ensureAiIncidentState(region){region.aiIncidentState||={};const s=region.aiIncidentState;s.incidents||=[];s.concealedIncidentIds||=[];s.reportedIncidentIds||=[];if(!Number.isFinite(s.diplomaticTrustPenalty))s.diplomaticTrustPenalty=0;return s;}

function applyIncidentEffects(region,incident){const s=incident.severity;if(incident.type===AI_INCIDENT_TYPES.INFRASTRUCTURE_DISRUPTION)region.aiGridDisruptionPressure=clamp((region.aiGridDisruptionPressure||0)+s*.24);if(incident.type===AI_INCIDENT_TYPES.FINANCIAL_DISRUPTION)region.aiFinancialInstabilityPressure=clamp((region.aiFinancialInstabilityPressure||0)+s*.22);if(incident.type===AI_INCIDENT_TYPES.INFORMATION_MANIPULATION)region.aiInformationIntegrityPressure=clamp((region.aiInformationIntegrityPressure||0)+s*.20);if(incident.type===AI_INCIDENT_TYPES.DATA_POISONING&&region.aiSystemicRisk?.pressures)region.aiSystemicRisk.pressures.objectiveFailure=clamp((region.aiSystemicRisk.pressures.objectiveFailure||0)+s*.16);if(incident.type===AI_INCIDENT_TYPES.MODEL_COMPROMISE&&region.aiSystemicRisk?.pressures)region.aiSystemicRisk.pressures.hostileCapture=clamp((region.aiSystemicRisk.pressures.hostileCapture||0)+s*.15);if(incident.type===AI_INCIDENT_TYPES.AUTHORISED_MISUSE&&region.aiSystemicRisk?.pressures)region.aiSystemicRisk.pressures.operatorMisuse=clamp((region.aiSystemicRisk.pressures.operatorMisuse||0)+s*.14);if(incident.type===AI_INCIDENT_TYPES.STRATEGIC_WARNING_ERROR)region.strategicAiCrisisPressure=clamp((region.strategicAiCrisisPressure||0)+s*.26);}

export function createAiIncident(region,{type=AI_INCIDENT_TYPES.DECISION_FAILURE,severity=.5,currentTick=0,cause='unknown',actualActorId=null,claimedActorId=null}={}){const spec=SPECS[type];if(!spec)throw new Error(`Unknown AI incident type ${type}`);const state=ensureAiIncidentState(region);const incident={id:`ai-incident-${nextIncidentId++}`,type,severity:clamp(severity),domain:spec.domain,createdTick:currentTick,status:'unresolved',cause,actualActorId,claimedActorId,reported:false,concealed:false,discovered:false,publicConfidence:0};state.incidents.push(incident);if(state.incidents.length>60)state.incidents.shift();applyIncidentEffects(region,incident);return incident;}

export function decideAiIncidentDisclosure(world,region,incident,currentTick=0,rng=Math.random){const g=ensureAiGovernance(region),treaty=hasMeasure(world,polityId(region),AI_GOVERNANCE_MEASURES.INCIDENT_REPORTING),visibility=clamp(SPECS[incident.type].publicVisibility+incident.severity*.36);const reportChance=clamp(g.policy.incidentReporting*.42+g.policy.transparency*.24+(treaty ? .20 : 0)+visibility*.28-g.policy.concealment*.34);const report=(rng?.()??Math.random())<reportChance;incident.reported=report;incident.concealed=!report;const state=ensureAiIncidentState(region);if(report){state.reportedIncidentIds.push(incident.id);incident.publicConfidence=clamp(.45+g.policy.transparency*.22+visibility*.18);recordInformationIncident(region,{id:`public-${incident.id}`,type:'ai_incident_report',headline:`AI incident reported in ${region.name||region.id}`,tick:currentTick,allegedActorId:incident.claimedActorId,sourceReliability:.72,provenance:.68,corroboration:.42,forensicSupport:.35,attributionEvidence:incident.claimedActorId ? .35 : 0,evidenceType:'official_report'});}else{state.concealedIncidentIds.push(incident.id);state.diplomaticTrustPenalty=clamp(state.diplomaticTrustPenalty+(treaty ? .06 : .02)*incident.severity);}return{reported:report,reportChance,treatyObligation:treaty,visibility};}

export function discoverConcealedAiIncident(world,region,incident,{source='inspection',confidence=.6,currentTick=0,allegedActorId=null}={}){if(!incident?.concealed)return{discovered:false,reason:'not_concealed'};incident.discovered=true;incident.status='disputed';incident.publicConfidence=clamp(confidence);const state=ensureAiIncidentState(region);state.diplomaticTrustPenalty=clamp(state.diplomaticTrustPenalty+.08*incident.severity);recordInformationIncident(region,{id:`discovery-${incident.id}`,type:'concealed_ai_incident',headline:`Evidence of an undisclosed AI incident emerges in ${region.name||region.id}`,tick:currentTick,allegedActorId,sourceReliability:clamp(confidence),provenance:source==='inspection' ? .72 : .48,corroboration:.46,forensicSupport:source==='inspection' ? .62 : .45,attributionEvidence:allegedActorId ? .40 : .10,evidenceType:source});return{discovered:true,incidentId:incident.id,confidence:incident.publicConfidence};}

export function requestAiInspection(world,accord,{requesterPolityId,targetPolityId,currentTick=0,reason='routine'}={},rng=Math.random){if(!accord?.active||!accord.memberPolityIds.includes(targetPolityId)||!accord.measures.includes(AI_GOVERNANCE_MEASURES.INSPECTION_RIGHTS))return{requested:false,reason:'no_inspection_rights'};const rs=regionsOf(world,targetPolityId);if(!rs.length)return{requested:false,reason:'no_target_regions'};const acceptance=weighted(rs,r=>ensureAiGovernance(r).policy.inspectionAcceptance),concealment=weighted(rs,r=>ensureAiGovernance(r).policy.concealment),pressure=reason==='suspected_violation' ? .16 : 0,acceptChance=clamp(.18+acceptance*.62+accord.verificationStrength*.14+pressure-concealment*.38),accepted=(rng?.()??Math.random())<acceptChance;accord.inspectionRequests||=[];const request={tick:currentTick,requesterPolityId,targetPolityId,reason,accepted,acceptChance};accord.inspectionRequests.push(request);if(accord.inspectionRequests.length>80)accord.inspectionRequests.shift();if(!accepted){for(const r of rs){const state=ensureAiIncidentState(r);state.diplomaticTrustPenalty=clamp(state.diplomaticTrustPenalty+.025+(reason==='suspected_violation' ? .035 : 0));}return{requested:true,accepted:false,...request};}const inspection=conductAiInspection(world,accord,targetPolityId,currentTick,rng);if(inspection.inspected&&inspection.discrepancyDetected){const hidden=rs.flatMap(r=>ensureAiIncidentState(r).incidents.map(i=>({region:r,incident:i}))).filter(x=>x.incident.concealed&&!x.incident.discovered).sort((a,b)=>b.incident.severity-a.incident.severity)[0];if(hidden)discoverConcealedAiIncident(world,hidden.region,hidden.incident,{source:'inspection',confidence:inspection.verificationConfidence,currentTick});}return{requested:true,accepted:true,...request,inspection};}

export function joinAiGovernanceAccord(world,accord,id,currentTick=0){if(!accord?.active||accord.memberPolityIds.includes(id)||!world.polities?.some(p=>p.id===id))return{joined:false,reason:'ineligible'};accord.memberPolityIds.push(id);accord.membershipHistory||=[];accord.membershipHistory.push({tick:currentTick,polityId:id,action:'joined'});return{joined:true};}
export function withdrawFromAiGovernanceAccord(world,accord,id,currentTick=0){const i=accord?.memberPolityIds?.indexOf(id)??-1;if(i<0)return{withdrawn:false,reason:'not_member'};accord.memberPolityIds.splice(i,1);accord.membershipHistory||=[];accord.membershipHistory.push({tick:currentTick,polityId:id,action:'withdrew'});return{withdrawn:true};}

function polityAssessment(world,id){const rs=regionsOf(world,id);if(!rs.length)return null;return{rs,capability:weighted(rs,aiCapability),competition:weighted(rs,r=>r.aiCompetitionPressure||r.strategicAiPressure||0),risk:weighted(rs,r=>r.aiSystemicRisk?.systemicRisk||0),transparency:weighted(rs,r=>ensureAiGovernance(r).policy.transparency),concealment:weighted(rs,r=>ensureAiGovernance(r).policy.concealment)};}
export function tickAiTreatyPolitics(world,currentTick=0,elapsedDays=30,rng=Math.random){const events=[];if(currentTick<=0||currentTick%13!==0)return events;for(const accord of world.aiGovernanceAccords||[]){if(!accord.active)continue;for(const polity of world.polities||[]){const a=polityAssessment(world,polity.id);if(!a||a.capability<.35)continue;const member=accord.memberPolityIds.includes(polity.id);if(member){const burden=clamp(accord.verificationStrength*.26+accord.exportControlCoordination*.22+a.competition*.34+a.concealment*.28),benefit=clamp(a.risk*.32+a.transparency*.24+(accord.measures.includes(AI_GOVERNANCE_MEASURES.EMERGENCY_HOTLINE) ? .12 : 0)+(accord.measures.includes(AI_GOVERNANCE_MEASURES.EVALUATION_STANDARDS) ? .10 : 0));if(burden-benefit>.34&&(rng?.()??Math.random())<.06+.16*(burden-benefit)){withdrawFromAiGovernanceAccord(world,accord,polity.id,currentTick);events.push({type:'ai_accord_withdrawal',accordId:accord.id,organisationId:accord.organisationId||accord.id,polityId:polity.id,playerRelevant:true});}}else{const attraction=clamp(a.risk*.36+a.transparency*.28+(1-a.competition)*.16-a.concealment*.22-accord.verificationStrength*.08);if(attraction>.42&&(rng?.()??Math.random())<.05+.15*attraction){joinAiGovernanceAccord(world,accord,polity.id,currentTick);events.push({type:'ai_accord_joined',accordId:accord.id,organisationId:accord.organisationId||accord.id,polityId:polity.id,playerRelevant:true});}}}}return events;}

function incidentHazard(region){const risk=region.aiSystemicRisk?.domainRisk||{},maxDomain=Math.max(0,...Object.values(risk).map(Number).filter(Number.isFinite));return clamp(maxDomain*.55+(region.aiControl?.incidentPressure||0)*.28+(region.aiDataIntegrityPressure||0)*.17);}
function pickIncidentType(region){const r=region.aiSystemicRisk?.domainRisk||{};return [['nuclearCommand',AI_INCIDENT_TYPES.STRATEGIC_WARNING_ERROR],['infrastructure',AI_INCIDENT_TYPES.INFRASTRUCTURE_DISRUPTION],['economy',AI_INCIDENT_TYPES.FINANCIAL_DISRUPTION],['information',AI_INCIDENT_TYPES.INFORMATION_MANIPULATION],['politicalPower',AI_INCIDENT_TYPES.AUTHORISED_MISUSE],['industry',AI_INCIDENT_TYPES.DECISION_FAILURE],['military',AI_INCIDENT_TYPES.MODEL_COMPROMISE]].sort((a,b)=>(r[b[0]]||0)-(r[a[0]]||0))[0]?.[1]||AI_INCIDENT_TYPES.DECISION_FAILURE;}

export function tickAiIncidentDiplomacy(world,currentTick=0,elapsedDays=7,rng=Math.random){const events=[],years=Math.max(0,Number(elapsedDays)||0)/365.2425;for(const region of world.regions||[]){if(aiCapability(region)<.25)continue;const hazard=incidentHazard(region),chance=1-Math.pow(1-clamp(hazard*.22,0,.75),years);if((rng?.()??Math.random())>=chance)continue;const incident=createAiIncident(region,{type:pickIncidentType(region),severity:clamp(.28+hazard*.62),currentTick,cause:'systemic'}),disclosure=decideAiIncidentDisclosure(world,region,incident,currentTick,rng);events.push({type:disclosure.reported?'ai_incident_reported':'ai_incident_concealed',incidentId:incident.id,polityId:polityId(region),regionId:region.id,severity:incident.severity,playerRelevant:true});const international=SPECS[incident.type].international*incident.severity;if(disclosure.reported&&international>.34)recordInternationalCrisisSignal(region,{id:`ai-crisis-${incident.id}`,type:'ai_incident',title:'International concern over AI incident',severity:clamp(international),evidence:incident.publicConfidence,sideAActorId:polityId(region),affectedActorId:polityId(region)});}events.push(...tickAiTreatyPolitics(world,currentTick,elapsedDays,rng));for(const accord of world.aiGovernanceAccords||[]){if(!accord.active||!accord.measures.includes(AI_GOVERNANCE_MEASURES.INSPECTION_RIGHTS)||currentTick<=0||currentTick%52!==0)continue;for(const id of [...accord.memberPolityIds]){const rs=regionsOf(world,id),suspect=rs.some(r=>ensureAiIncidentState(r).concealedIncidentIds.length>0)||weighted(rs,r=>ensureAiIncidentState(r).diplomaticTrustPenalty)>.08,requester=accord.memberPolityIds.find(x=>x!==id)||accord.organisationId||null,result=requestAiInspection(world,accord,{requesterPolityId:requester,targetPolityId:id,currentTick,reason:suspect?'suspected_violation':'routine'},rng);if(result.requested&&!result.accepted){events.push({type:'ai_inspection_refused',accordId:accord.id,organisationId:accord.organisationId||accord.id,targetPolityId:id,polityId:id,playerRelevant:true,reason:suspect?'suspected_violation':'routine'});if(suspect&&rs[0])recordInternationalCrisisSignal(rs[0],{id:`ai-inspection-refusal-${accord.id}-${id}-${currentTick}`,type:'ai_governance_dispute',title:'AI inspection refused amid compliance concerns',severity:.48,evidence:.42,sideAActorId:id,affectedActorId:requester});}else if(result.accepted&&result.inspection?.discrepancyDetected)events.push({type:'ai_inspection_discrepancy',accordId:accord.id,organisationId:accord.organisationId||accord.id,targetPolityId:id,polityId:id,playerRelevant:true,verificationConfidence:result.inspection.verificationConfidence});}}return events;}
